import type { BirdRule, StateData } from "./types";

const duckRules = (pintailLimit = 3, scaupLimit = 1): BirdRule[] => [
  { id: "mallard-drake", label: "Mallard — Drake", group: "Ducks", limit: 4, sex: "Drake", parent: "mallard", parentLimit: 4, note: "Counts toward the 4-mallard and 6-duck limits." },
  { id: "mallard-hen", label: "Mallard — Hen", group: "Ducks", limit: 2, sex: "Hen", parent: "mallard", parentLimit: 4, note: "Maximum 2 hens; counts toward 4 mallards." },
  { id: "black-duck", label: "American Black Duck", group: "Ducks", limit: 2 },
  { id: "wood-duck", label: "Wood Duck", group: "Ducks", limit: 3 },
  { id: "pintail", label: "Northern Pintail", group: "Ducks", limit: pintailLimit },
  { id: "redhead", label: "Redhead", group: "Ducks", limit: 2 },
  { id: "canvasback", label: "Canvasback", group: "Ducks", limit: 2 },
  { id: "scaup", label: "Scaup", group: "Ducks", limit: scaupLimit, note: "The daily limit changes during designated season dates; verify the selected date." },
  { id: "sea-duck", label: "Sea Duck", group: "Ducks", limit: 4, note: "Scoter, eider and long-tailed duck sublimits apply." },
  { id: "other-duck", label: "Other legal duck", group: "Ducks", limit: 6 },
  { id: "coot", label: "Coot", group: "Other", limit: 15 },
];

const sources = {
  MD: "https://dnr.maryland.gov/wildlife/Pages/hunt_trap/waterfowl.aspx",
  DE: "https://dnrec.delaware.gov/fish-wildlife/hunting/",
  VA: "https://dwr.virginia.gov/hunting/regulations/migratory-gamebirds/",
  NC: "https://www.ncwildlife.gov/hunting/hunting-regulations",
  WV: "https://wvdnr.gov/wp-content/uploads/2025/06/Pub_Regs_MigratoryBird2025_DNR_WILD_digital_readerspreads_pp.pdf",
  PA: "https://www.pa.gov/agencies/pgc/newsroom/2026-27-migratory-game-bird-season-set",
  NY: "https://dec.ny.gov/things-to-do/hunting/migratory-game-bird/seasons",
  SC: "https://www.dnr.sc.gov/hunting/SCMigratoryBirdSeasons.pdf",
  LA: "https://www.wlf.louisiana.gov/page/seasons-and-regulations",
  TX: "https://tpwd.texas.gov/regulations/outdoor-annual/regs/animal_listing",
  AR: "https://www.agfc.com/hunting/waterfowl/waterfowl-dates-rules-regulations/",
  ND: "https://gf.nd.gov/regulations/small-game",
};

export const states: StateData[] = [
  {
    code: "MD", name: "Maryland", seasonYear: "Demo package", dataStatus: "demo",
    verifiedLabel: "Demo season package • verify current DNR rules", officialUrl: sources.MD,
    shootingHours: "Generally ½ hour before sunrise to sunset; exceptions apply.",
    overview: "Eastern and Western duck zones, plus goose population zones and special sea-duck rules.",
    zones: ["Eastern Duck Zone", "Western Duck Zone", "Atlantic Population Goose Zone"],
    seasons: [
      { name: "Regular Duck", dates: "Oct 11–18 • Nov 15–28 • Dec 16–Jan 31", open: false, zone: "Eastern Duck Zone" },
      { name: "Sea Ducks", dates: "Nov 8–Jan 10", open: false, zone: "Special Sea Duck Area" },
      { name: "Canada Goose", dates: "Nov 22–28 • Dec 16–Jan 31", open: false, zone: "AP Goose Zone" },
      { name: "Snow Goose", dates: "Oct 1–Jan 31", open: false, zone: "Statewide" },
    ],
    birds: [...duckRules(1), { id: "canada-goose", label: "Canada Goose", group: "Geese", limit: 2 }, { id: "snow-goose", label: "Snow / Ross’s Goose", group: "Geese", limit: 25 }, { id: "brant", label: "Brant", group: "Geese", limit: 1 }],
  },
  {
    code: "DE", name: "Delaware", seasonYear: "Demo package", dataStatus: "demo",
    verifiedLabel: "Demo season package • verify current DNREC rules", officialUrl: sources.DE,
    shootingHours: "Generally ½ hour before sunrise to sunset; exceptions apply.",
    overview: "Statewide duck dates with separate goose zones, special-area rules, and public-area permits.",
    zones: ["Statewide Duck Zone", "AP Canada Goose Zone", "Special Sea Duck Area"],
    seasons: [
      { name: "Regular Duck", dates: "Oct 24–Nov 1 • Nov 24–29 • Dec 12–Jan 31", open: false, zone: "Statewide" },
      { name: "Canada Goose", dates: "Nov 24–29 • Dec 12–Jan 31", open: false, zone: "AP Zone" },
      { name: "Snow Goose", dates: "Oct 1–Jan 31", open: false, zone: "Statewide" },
    ],
    birds: [...duckRules(1), { id: "canada-goose", label: "Canada Goose", group: "Geese", limit: 2 }, { id: "snow-goose", label: "Snow / Ross’s Goose", group: "Geese", limit: 25 }],
  },
  {
    code: "VA", name: "Virginia", seasonYear: "Demo package", dataStatus: "demo",
    verifiedLabel: "Demo season package • verify current DWR rules", officialUrl: sources.VA,
    shootingHours: "Generally ½ hour before sunrise to sunset; exceptions apply.",
    overview: "Duck seasons are statewide; Canada goose rules vary among AP, resident, and special zones.",
    zones: ["Statewide Duck Zone", "Atlantic Population Zone", "Resident Population Zone"],
    seasons: [
      { name: "Regular Duck", dates: "Oct 10–13 • Nov 19–30 • Dec 19–Jan 31", open: false, zone: "Statewide" },
      { name: "Canada Goose", dates: "Nov 19–30 • Dec 19–Jan 31", open: false, zone: "Varies by goose zone" },
      { name: "Light Goose", dates: "Oct 17–Jan 31", open: false, zone: "Statewide" },
    ],
    birds: [...duckRules(1), { id: "canada-goose", label: "Canada Goose", group: "Geese", limit: 2 }, { id: "light-goose", label: "Snow / Blue Goose", group: "Geese", limit: 25 }, { id: "brant", label: "Brant", group: "Geese", limit: 1 }],
  },
  {
    code: "NC", name: "North Carolina", seasonYear: "Demo package", dataStatus: "demo",
    verifiedLabel: "Demo season package • verify current Wildlife Commission rules", officialUrl: sources.NC,
    shootingHours: "Generally ½ hour before sunrise to sunset; exceptions apply.",
    overview: "Statewide duck framework with Canada goose zones and permit-only waterfowl opportunities.",
    zones: ["Statewide Duck Zone", "Northeast Hunt Zone", "Resident Population Zone"],
    seasons: [
      { name: "Regular Duck", dates: "Oct 2–4 • Nov 15–29 • Dec 13–Jan 31", open: false, zone: "Statewide" },
      { name: "Canada Goose", dates: "Varies by management zone", open: false, zone: "Select zone" },
      { name: "Light Goose", dates: "Oct 14–Feb 14", open: false, zone: "Statewide" },
    ],
    birds: [...duckRules(1), { id: "canada-goose", label: "Canada Goose", group: "Geese", limit: 5 }, { id: "light-goose", label: "Snow / Ross’s Goose", group: "Geese", limit: 25 }, { id: "brant", label: "Brant", group: "Geese", limit: 1 }],
  },
  {
    code: "PA", name: "Pennsylvania", seasonYear: "2026–2027", dataStatus: "current",
    verifiedLabel: "2026–2027 • official PGC season package", officialUrl: sources.PA,
    shootingHours: "Generally ½ hour before sunrise to sunset. Migratory game bird hunting is closed on Sundays.",
    overview: "Four duck zones, two Canada goose population zones, zone- and date-specific scaup rules, and no Sunday migratory-bird hunting.",
    zones: ["North Duck Zone", "South Duck Zone", "Northwest Duck Zone", "Lake Erie Duck Zone", "Resident Population Goose Zone", "Atlantic Population Goose Zone"],
    seasons: [
      { name: "Ducks, sea ducks, coots & mergansers", dates: "Oct 10–24 • Nov 17–Jan 9", open: false, zone: "North Duck Zone" },
      { name: "Ducks, sea ducks, coots & mergansers", dates: "Oct 10–17 • Nov 18–Jan 18", open: false, zone: "South Duck Zone" },
      { name: "Ducks, sea ducks, coots & mergansers", dates: "Oct 10–Nov 27 • Dec 21–Jan 9", open: false, zone: "Northwest Duck Zone" },
      { name: "Ducks, sea ducks, coots & mergansers", dates: "Nov 2–Jan 9", open: false, zone: "Lake Erie Duck Zone" },
      { name: "Canada Goose — Regular", dates: "Oct 24–Nov 27 • Dec 15–Jan 18 • Jan 29–Feb 20", open: false, zone: "Resident Population Goose Zone" },
      { name: "Canada Goose — Regular", dates: "Nov 21–27 • Dec 4–Jan 18", open: false, zone: "Atlantic Population Goose Zone" },
      { name: "Light Geese", dates: "Nov 6–Mar 10", open: false, zone: "All goose zones" },
      { name: "Brant", dates: "Oct 10–Nov 13", open: false, zone: "All zones" },
    ],
    birds: [...duckRules(3),
      { id: "merganser", label: "Merganser", group: "Ducks", limit: 5 },
      { id: "canada-goose", label: "Canada / White-fronted Goose", group: "Geese", limit: 3, zoneLimits: { "Resident Population Goose Zone": 5, "Atlantic Population Goose Zone": 3 }, note: "Regular-season limit; September and special-segment limits differ." },
      { id: "light-goose", label: "Snow / Ross’s Goose", group: "Geese", limit: 25 },
      { id: "brant", label: "Brant", group: "Geese", limit: 1 },
    ],
  },
  {
    code: "NY", name: "New York", seasonYear: "2026–2027", dataStatus: "current",
    verifiedLabel: "2026–2027 • official NYSDEC season package", officialUrl: sources.NY,
    shootingHours: "Generally ½ hour before sunrise to sunset. September Canada goose exceptions apply.",
    overview: "Five duck zones and nine Canada goose areas with separate season segments, limits, youth days and military days.",
    zones: ["Western Waterfowl Zone", "Northeast Waterfowl Zone", "Lake Champlain Waterfowl Zone", "Southeast Waterfowl Zone", "Long Island Waterfowl Zone", "Northeast Goose Area", "West Central Goose Area", "East Central Goose Area", "Hudson Valley Goose Area", "Lake Champlain Goose Area", "South Goose Area", "Western Long Island Goose Area", "Central Long Island Goose Area", "Eastern Long Island Goose Area"],
    seasons: [
      { name: "Ducks, coots & mergansers", dates: "Oct 10–Nov 1 • Dec 5–Jan 10", open: false, zone: "Western Waterfowl Zone" },
      { name: "Ducks, coots & mergansers", dates: "Oct 10–Nov 29 • Dec 12–20", open: false, zone: "Northeast Waterfowl Zone" },
      { name: "Ducks, coots & mergansers", dates: "Oct 10–Nov 1 • Nov 21–Dec 27", open: false, zone: "Lake Champlain Waterfowl Zone" },
      { name: "Ducks, coots & mergansers", dates: "Oct 10–18 • Nov 7–Dec 27", open: false, zone: "Southeast Waterfowl Zone" },
      { name: "Ducks, coots & mergansers", dates: "Nov 21–29 • Dec 12–Jan 31", open: false, zone: "Long Island Waterfowl Zone" },
      { name: "Canada Goose", dates: "Dates and limits vary across nine goose areas", open: false, zone: "Select a goose area" },
      { name: "Snow Goose", dates: "Zone-specific dates through Mar 10", open: false, zone: "Select waterfowl zone" },
      { name: "Brant", dates: "Oct 10–Nov 8; Long Island Jan 2–31", open: false, zone: "Zone-specific" },
    ],
    birds: [...duckRules(3),
      { id: "merganser", label: "Merganser", group: "Ducks", limit: 6, note: "Included in New York's aggregate six-bird duck bag." },
      { id: "canada-goose", label: "Canada / White-fronted Goose", group: "Geese", limit: 3, zoneLimits: { "Northeast Goose Area": 3, "West Central Goose Area": 3, "East Central Goose Area": 3, "Hudson Valley Goose Area": 3, "Lake Champlain Goose Area": 3, "South Goose Area": 5, "Western Long Island Goose Area": 8, "Central Long Island Goose Area": 3, "Eastern Long Island Goose Area": 2 }, note: "Regular-season limit; September and special-season limits differ." },
      { id: "snow-goose", label: "Snow / Ross’s Goose", group: "Geese", limit: 25 },
      { id: "brant", label: "Brant", group: "Geese", limit: 1 },
    ],
  },
  {
    code: "WV", name: "West Virginia", seasonYear: "2025–2026 reference", dataStatus: "archived",
    dataNotice: "West Virginia’s 2026–2027 migratory-bird guide has not been released. These expired 2025–2026 dates are displayed for planning reference only and must not be used to determine current legality.",
    verifiedLabel: "Archived 2025–2026 WVDNR package • update pending", officialUrl: sources.WV,
    shootingHours: "Generally ½ hour before sunrise to sunset; WMA and concurrent-season restrictions apply.",
    overview: "Archived statewide migratory-bird package. The 2026–2027 WVDNR migratory guide is expected by the end of August 2026.",
    zones: ["Statewide"],
    seasons: [
      { name: "Youth Waterfowl", dates: "Sept 20 • Nov 1, 2025", open: false, zone: "Statewide — archived" },
      { name: "Regular Duck", dates: "Oct 4–12 • Nov 8–16 • Dec 21–Jan 31", open: false, zone: "Statewide — 2025–2026" },
      { name: "Canada / White-fronted Goose", dates: "Oct 4–19 • Nov 8–16 • Dec 8–Jan 31", open: false, zone: "Statewide — 2025–2026" },
      { name: "Early Canada Goose", dates: "Sept 1–14, 2025", open: false, zone: "Statewide — archived" },
      { name: "Snow / Blue Goose", dates: "Oct 4–19 • Nov 8–16 • Dec 8–Jan 31", open: false, zone: "Statewide — 2025–2026" },
      { name: "Brant", dates: "Jan 2–31, 2026", open: false, zone: "Statewide — archived" },
    ],
    birds: [...duckRules(3),
      { id: "merganser", label: "Merganser", group: "Ducks", limit: 5 },
      { id: "canada-goose", label: "Canada / White-fronted Goose", group: "Geese", limit: 5 },
      { id: "snow-goose", label: "Snow / Blue Goose", group: "Geese", limit: 5 },
      { id: "brant", label: "Brant", group: "Geese", limit: 1 },
    ],
  },
  {
    code: "SC", name: "South Carolina", seasonYear: "2025–2026 reference", dataStatus: "archived",
    dataNotice: "South Carolina’s 2026–2027 migratory-bird package has not been loaded. These expired 2025–2026 dates are for planning reference only and must not be used to determine current legality.",
    verifiedLabel: "Archived 2025–2026 SCDNR package • update pending", officialUrl: sources.SC,
    shootingHours: "Generally ½ hour before sunrise to sunset. Early teal ran sunrise to sunset; special-area rules apply.",
    overview: "Archived statewide package with early teal, special sea-duck rules and black/mottled-duck limits that differ east and west of I-95.",
    zones: ["Statewide", "East of I-95", "West of I-95", "Special Sea Duck Area"],
    seasons: [
      { name: "Early Teal", dates: "Sept 20–28, 2025", open: false, zone: "Statewide — archived" },
      { name: "Regular Duck", dates: "Nov 22–29 • Dec 12–Jan 31", open: false, zone: "Statewide — 2025–2026" },
      { name: "Early Canada Goose", dates: "Sept 1–30, 2025", open: false, zone: "Statewide — archived" },
      { name: "Canada / White-fronted Goose", dates: "Nov 22–29 • Dec 12–Jan 31 • Feb 15–Mar 1", open: false, zone: "Statewide — 2025–2026" },
      { name: "Blue / Snow Goose", dates: "Nov 22–29 • Dec 12–Jan 31 • Feb 15–Mar 1", open: false, zone: "Statewide — 2025–2026" },
      { name: "Brant", dates: "Jan 2–31, 2026", open: false, zone: "Statewide — archived" },
    ],
    birds: [...duckRules(3),
      { id: "mottled-duck", label: "Mottled Duck", group: "Ducks", limit: 1 },
      { id: "black-bellied-whistling", label: "Black-bellied Whistling Duck", group: "Ducks", limit: 1 },
      { id: "fulvous-whistling", label: "Fulvous Whistling Duck", group: "Ducks", limit: 1 },
      { id: "merganser", label: "Merganser", group: "Ducks", limit: 5, note: "No more than one hooded merganser." },
      { id: "canada-goose", label: "Canada Goose", group: "Geese", limit: 5 },
      { id: "white-fronted-goose", label: "White-fronted Goose", group: "Geese", limit: 2, note: "Counts toward the five-goose Canada/white-fronted aggregate limit." },
      { id: "snow-goose", label: "Snow / Blue Goose", group: "Geese", limit: 25 },
      { id: "brant", label: "Brant", group: "Geese", limit: 1 },
    ],
  },
  {
    code: "LA", name: "Louisiana", seasonYear: "2026–2027", dataStatus: "current",
    verifiedLabel: "2026–2027 • official LDWF migratory-bird package", officialUrl: sources.LA,
    shootingHours: "Generally ½ hour before sunrise to sunset. Early teal begins at sunrise; Conservation Order hours extend to ½ hour after sunset.",
    overview: "East and West waterfowl zones with date-dependent scaup and mottled-duck rules, plus a separate permitted black-bellied whistling-duck season.",
    zones: ["East Waterfowl Zone", "West Waterfowl Zone"],
    seasons: [
      { name: "Early Teal", dates: "Sept 19–27, 2026", open: false, zone: "Statewide" },
      { name: "Black-bellied Whistling Duck", dates: "Oct 3–11, 2026", open: false, zone: "Statewide — free permit required" },
      { name: "Regular Duck", dates: "Nov 21–Dec 6 • Dec 19–Jan 31", open: false, zone: "East Waterfowl Zone" },
      { name: "Regular Duck", dates: "Nov 14–Dec 6 • Dec 19–Jan 24", open: false, zone: "West Waterfowl Zone" },
      { name: "Dark & Light Geese", dates: "Nov 14–Dec 6 • Dec 19–Feb 7", open: false, zone: "East & West Zones" },
      { name: "Light Goose Conservation Order", dates: "Dec 7–18 • Feb 8–Mar 7", open: false, zone: "East & West Zones" },
    ],
    specialRules: [
      "Only one scaup may be taken during the first 15 days of each zone's regular season; two are allowed afterward.",
      "Mottled ducks are closed during the first 15 days of each zone's regular season; one is allowed afterward.",
      "The three-pintail limit may include no more than one female pintail.",
      "A free LDWF Black-bellied Whistling Duck Permit is required for the October 3–11 season.",
      "Light Goose Conservation Order permits electronic calls, unplugged shotguns and has no daily or possession limit.",
    ],
    birds: [
      { id: "mallard-drake", label: "Mallard — Drake", group: "Ducks", limit: 4, sex: "Drake", parent: "mallard", parentLimit: 4 },
      { id: "mallard-hen", label: "Mallard — Hen", group: "Ducks", limit: 2, sex: "Hen", parent: "mallard", parentLimit: 4 },
      { id: "wood-duck", label: "Wood Duck", group: "Ducks", limit: 3 },
      { id: "pintail-drake", label: "Northern Pintail — Drake", group: "Ducks", limit: 3, sex: "Drake", parent: "pintail", parentLimit: 3 },
      { id: "pintail-hen", label: "Northern Pintail — Hen", group: "Ducks", limit: 1, sex: "Hen", parent: "pintail", parentLimit: 3 },
      { id: "black-duck", label: "American Black Duck", group: "Ducks", limit: 1 },
      { id: "mottled-duck", label: "Mottled Duck", group: "Ducks", limit: 1, note: "Closed for the first 15 days of regular season." },
      { id: "redhead", label: "Redhead", group: "Ducks", limit: 2 },
      { id: "canvasback", label: "Canvasback", group: "Ducks", limit: 2 },
      { id: "scaup", label: "Scaup", group: "Ducks", limit: 1, note: "One during the first 15 days; two afterward." },
      { id: "other-duck", label: "Other legal duck", group: "Ducks", limit: 6 },
      { id: "black-bellied-whistling", label: "Black-bellied Whistling Duck", group: "Ducks", limit: 4, note: "Separate October season and free permit required." },
      { id: "merganser", label: "Merganser", group: "Ducks", limit: 5, note: "No more than two hooded mergansers." },
      { id: "coot", label: "Coot", group: "Other", limit: 15 },
      { id: "canada-goose", label: "Canada Goose", group: "Geese", limit: 1 },
      { id: "white-fronted-goose", label: "White-fronted Goose", group: "Geese", limit: 3 },
      { id: "light-goose", label: "Snow / Blue / Ross’s Goose", group: "Geese", limit: 20 },
    ],
  },
  {
    code: "TX", name: "Texas", seasonYear: "2026–2027", dataStatus: "current",
    verifiedLabel: "2026–2027 • official TPWD Outdoor Annual", officialUrl: sources.TX,
    shootingHours: "Generally ½ hour before sunrise to sunset. County and special-season exceptions may apply.",
    overview: "Three duck zones and two goose zones. County selection ultimately determines the correct zone; dusky ducks are closed for each zone's first five regular-season days.",
    zones: ["High Plains Mallard Management Unit", "North Duck Zone", "South Duck Zone", "Eastern Goose Zone", "Western Goose Zone"],
    seasons: [
      { name: "Early Teal", dates: "Sept 19–27, 2026", open: false, zone: "Statewide" },
      { name: "Regular Duck", dates: "Oct 24–25 • Oct 30–Jan 31", open: false, zone: "High Plains Mallard Management Unit" },
      { name: "Regular Duck", dates: "Nov 14–29 • Dec 5–Jan 31", open: false, zone: "North Duck Zone" },
      { name: "Regular Duck", dates: "Nov 7–29 • Dec 12–Jan 31", open: false, zone: "South Duck Zone" },
      { name: "Early Canada Goose", dates: "Sept 12–27", open: false, zone: "Eastern Goose Zone" },
      { name: "Dark Geese", dates: "Nov 7–Jan 31", open: false, zone: "Eastern Goose Zone" },
      { name: "Dark Geese", dates: "Nov 7–Feb 7", open: false, zone: "Western Goose Zone" },
      { name: "Light Geese", dates: "Nov 7–Feb 19 East • Nov 7–Feb 7 West", open: false, zone: "Select goose zone" },
    ],
    specialRules: [
      "Dusky ducks—mottled, Mexican, black ducks and their hybrids—are closed during the first five days of regular duck season in each zone.",
      "Texas regulations are county-based; verify that the selected zone matches the county where the hunt occurs.",
      "The aggregate duck limit includes mergansers.",
      "Migratory Game Bird Endorsement, HIP certification and Federal Duck Stamp requirements apply.",
    ],
    birds: [
      { id: "mallard-drake", label: "Mallard — Drake", group: "Ducks", limit: 5, sex: "Drake", parent: "mallard", parentLimit: 5 },
      { id: "mallard-hen", label: "Mallard — Hen", group: "Ducks", limit: 2, sex: "Hen", parent: "mallard", parentLimit: 5 },
      { id: "wood-duck", label: "Wood Duck", group: "Ducks", limit: 3 },
      { id: "pintail", label: "Northern Pintail", group: "Ducks", limit: 3 },
      { id: "redhead", label: "Redhead", group: "Ducks", limit: 2 },
      { id: "canvasback", label: "Canvasback", group: "Ducks", limit: 2 },
      { id: "scaup", label: "Scaup", group: "Ducks", limit: 1 },
      { id: "dusky-duck", label: "Dusky Duck", group: "Ducks", limit: 1, note: "Closed during the first five regular-season days in each zone." },
      { id: "merganser", label: "Merganser", group: "Ducks", limit: 6, note: "Included in the aggregate six-duck limit." },
      { id: "other-duck", label: "Other legal duck", group: "Ducks", limit: 6 },
      { id: "coot", label: "Coot", group: "Other", limit: 15 },
      { id: "dark-goose", label: "Dark Goose", group: "Geese", limit: 5, note: "Eastern Zone may include no more than two white-fronted geese." },
      { id: "light-goose", label: "Light Goose", group: "Geese", limit: 5 },
    ],
  },
  {
    code: "AR", name: "Arkansas", seasonYear: "2026–2027", dataStatus: "current",
    verifiedLabel: "2026–2027 • official AGFC waterfowl package", officialUrl: sources.AR,
    shootingHours: "Generally 30 minutes before sunrise to sunset; most WMAs close regular waterfowl hunting at noon and impose departure deadlines.",
    overview: "Statewide waterfowl seasons with extensive WMA-specific permits, access restrictions, noon closures and departure-time requirements.",
    zones: ["Statewide", "AGFC Wildlife Management Area"],
    seasons: [
      { name: "Early Teal", dates: "Sept 19–27, 2026", open: false, zone: "Statewide" },
      { name: "Duck, Coot & Merganser", dates: "Nov 21–29 • Dec 10–23 • Dec 26–Jan 31", open: false, zone: "Statewide" },
      { name: "Youth, Veteran & Military", dates: "Feb 6–7, 2027", open: false, zone: "Statewide" },
      { name: "Early Canada Goose", dates: "Sept 1–Oct 15", open: false, zone: "Statewide" },
      { name: "Regular Canada Goose", dates: "Nov 21–29 • Dec 10–23 • Dec 26–Jan 31", open: false, zone: "Statewide" },
      { name: "White-fronted & Light Geese", dates: "Oct 31–Nov 8 • Nov 21–29 • Dec 10–23 • Dec 26–Jan 31", open: false, zone: "Statewide" },
      { name: "Light Goose Conservation Order", dates: "Feb 1–5 • Feb 8–Apr 25", open: false, zone: "Statewide" },
    ],
    specialRules: [
      "Most AGFC WMAs end regular waterfowl shooting at noon, with separate deadlines for leaving water-inundated areas.",
      "WMA-specific permit, boat, access and nonresident restrictions must be checked before hunting.",
      "Early Canada goose limit is five; the regular-season Canada goose limit is two.",
      "A valid Arkansas hunting license and state duck stamp are required for the Light Goose Conservation Order.",
      "Federally approved nontoxic shot is required for ducks, geese and mergansers statewide.",
    ],
    birds: [
      ...duckRules(3),
      { id: "mottled-duck", label: "Mottled Duck", group: "Ducks", limit: 1 },
      { id: "merganser", label: "Merganser", group: "Ducks", limit: 5, note: "No more than two hooded mergansers." },
      { id: "canada-goose", label: "Canada Goose", group: "Geese", limit: 2, note: "Regular season; early-season limit is five." },
      { id: "white-fronted-goose", label: "White-fronted Goose", group: "Geese", limit: 2 },
      { id: "light-goose", label: "Snow / Blue / Ross’s Goose", group: "Geese", limit: 20 },
    ],
  },
  {
    code: "ND", name: "North Dakota", seasonYear: "2026–2027", dataStatus: "current",
    verifiedLabel: "2026–2027 • official NDGF proclamation", officialUrl: sources.ND,
    shootingHours: "Ducks: generally ½ hour before sunrise to sunset. Regular goose hours often end at 2 p.m. until expanded on specified days and later in the season.",
    overview: "High and Low Plains duck units, three Canada goose zones, resident/nonresident opening differences, nonresident license zones and a bonus blue-winged teal period.",
    zones: ["Low Plains Duck Unit", "High Plains Duck Unit", "Missouri River Canada Goose Zone", "Western Canada Goose Zone", "Eastern Canada Goose Zone"],
    seasons: [
      { name: "Youth, Veteran & Military Waterfowl", dates: "Sept 19–20, 2026", open: false, zone: "Statewide" },
      { name: "Resident Duck", dates: "Sept 26–Dec 6", open: false, zone: "Low Plains Duck Unit" },
      { name: "Resident Duck", dates: "Sept 26–Dec 6 • Dec 12–Jan 3", open: false, zone: "High Plains Duck Unit" },
      { name: "Nonresident Duck", dates: "Begins Oct 5; licensed zone restrictions apply", open: false, zone: "Selected nonresident license zone" },
      { name: "Bonus Blue-winged Teal", dates: "Sept 26–Oct 4", open: false, zone: "All duck units" },
      { name: "Early Canada Goose", dates: "Aug 15–Sept 7 Missouri River • Aug 15–Sept 15 West • Aug 15–Sept 22 East", open: false, zone: "Select goose zone" },
      { name: "Regular Canada Goose", dates: "Sept 26–Jan 1 Missouri River • through Dec 24 West • through Dec 19 East", open: false, zone: "Select goose zone" },
      { name: "White-fronted Goose", dates: "Sept 26–Dec 6", open: false, zone: "Statewide" },
      { name: "Light Goose", dates: "Sept 26–Jan 3", open: false, zone: "Statewide" },
    ],
    specialRules: [
      "Residents begin regular waterfowl hunting September 26; nonresidents begin October 5 and must remain within the zone selected for their license.",
      "Two bonus blue-winged teal may be taken in addition to the regular six-duck limit from September 26 through October 4.",
      "Regular goose shooting generally closes at 2 p.m.; specified Wednesdays and Saturdays have sunset closure through November 28, and all days extend to sunset beginning November 29.",
      "A motorized floating craft must be at rest with its motor turned off before migratory game birds may be taken.",
      "Electronic or recorded calls are prohibited for waterfowl during regular seasons.",
    ],
    birds: [
      { id: "mallard-drake", label: "Mallard — Drake", group: "Ducks", limit: 5, sex: "Drake", parent: "mallard", parentLimit: 5 },
      { id: "mallard-hen", label: "Mallard — Hen", group: "Ducks", limit: 2, sex: "Hen", parent: "mallard", parentLimit: 5 },
      { id: "wood-duck", label: "Wood Duck", group: "Ducks", limit: 3 },
      { id: "pintail", label: "Northern Pintail", group: "Ducks", limit: 3 },
      { id: "redhead", label: "Redhead", group: "Ducks", limit: 2 },
      { id: "canvasback", label: "Canvasback", group: "Ducks", limit: 2 },
      { id: "scaup", label: "Scaup", group: "Ducks", limit: 1 },
      { id: "other-duck", label: "Other legal duck", group: "Ducks", limit: 6 },
      { id: "bonus-bluewing-teal", label: "Bonus Blue-winged Teal", group: "Other", limit: 2, note: "Additional to the six-duck bag only Sept 26–Oct 4." },
      { id: "coot", label: "Coot", group: "Other", limit: 15 },
      { id: "canada-goose", label: "Canada Goose", group: "Geese", limit: 5, zoneLimits: { "Missouri River Canada Goose Zone": 5, "Western Canada Goose Zone": 8, "Eastern Canada Goose Zone": 8 }, note: "Regular-season limits. Early-season limit is 15 in all three zones." },
      { id: "white-fronted-goose", label: "White-fronted Goose", group: "Geese", limit: 3 },
      { id: "light-goose", label: "Light Goose", group: "Geese", limit: 50 },
    ],
  },
];
