import type { BirdRule, StateData } from "./types";

const duckRules = (pintailLimit = 3, scaupLimit = 1): BirdRule[] => [
  { id: "mallard-drake", label: "Mallard — Drake", group: "Ducks", limit: 4, sex: "Drake", parent: "mallard", parentLimit: 4, note: "Counts toward the 4-mallard and 6-duck limits." },
  { id: "mallard-hen", label: "Mallard — Hen", group: "Ducks", limit: 2, sex: "Hen", parent: "mallard", parentLimit: 4, note: "Maximum 2 hens; counts toward 4 mallards." },
  { id: "black-duck", label: "American Black Duck", group: "Ducks", limit: 2 },
  { id: "wood-duck", label: "Wood Duck", group: "Ducks", limit: 3 },
  { id: "pintail", label: "Northern Pintail", group: "Ducks", limit: pintailLimit },
  { id: "redhead", label: "Redhead", group: "Ducks", limit: 2 },
  { id: "canvasback", label: "Canvasback", group: "Ducks", limit: 2 },
  { id: "scaup", label: "Scaup", group: "Ducks", limit: scaupLimit, note: "The daily limit changes during designated season dates; verify the selected date." },
  { id: "sea-duck", label: "Sea Duck", group: "Ducks", limit: 4, note: "Scoter, eider and long-tailed duck sublimits apply." },
  { id: "other-duck", label: "Other legal duck", group: "Ducks", limit: 6 },
  { id: "coot", label: "Coot", group: "Other", limit: 15 },
];

const sources = {
  MD: "https://dnr.maryland.gov/wildlife/Pages/hunt_trap/waterfowl.aspx",
  DE: "https://dnrec.delaware.gov/fish-wildlife/hunting/",
  VA: "https://dwr.virginia.gov/hunting/regulations/migratory-gamebirds/",
  NC: "https://www.ncwildlife.gov/hunting/hunting-regulations",
  WV: "https://wvdnr.gov/west-virginia-unveils-new-dates-for-dove-woodcock-and-rail-hunting-seasons/",
  PA: "https://www.pa.gov/agencies/pgc/newsroom/2026-27-migratory-game-bird-season-set",
  NY: "https://dec.ny.gov/things-to-do/hunting/migratory-game-bird/seasons",
  SC: "https://www.eregulations.com/assets/docs/resources/SC/26SCAB_LR.pdf",
  LA: "https://www.wlf.louisiana.gov/page/seasons-and-regulations",
  TX: "https://tpwd.texas.gov/regulations/outdoor-annual/regs/animal_listing",
  AR: "https://www.agfc.com/hunting/waterfowl/waterfowl-dates-rules-regulations/",
  ND: "https://gf.nd.gov/regulations/small-game",
  WI: "https://dnr.wisconsin.gov/topic/Hunt/regulations/OnlineHuntingRegulations?page=8",
  IL: "https://dnr.illinois.gov/hunting/waterfowlhunting.html",
  MT: "https://fwp.mt.gov/hunt/regulations/migratory-bird",
  MN: "https://www.dnr.state.mn.us/gohunting/duck-and-goose-hunting.html",
  KS: "https://www.ksoutdoors.gov/outdoor-activities/hunting-in-kansas/what-to-hunt/migratory-birds/ducks",
};

export const states: StateData[] = [
  {
    code: "MD", name: "Maryland", seasonYear: "2026–2027 provisional", dataStatus: "tentative",
    dataNotice: "Maryland has published a complete 2026–2027 season table, but the state labels the dates and limits contingent on U.S. Fish and Wildlife Service approval. BlindIQ will recheck the Maryland DNR final package in September.",
    verifiedLabel: "Published 2026–2027 package • federal approval pending", officialUrl: sources.MD,
    sourceLinks: [
      { label: "Maryland DNR waterfowl page", url: sources.MD },
      { label: "2026–27 eRegulations season table", url: "https://www.eregulations.com/maryland/hunting/migratory-game-bird-seasons-limits" },
    ],
    shootingHours: "Generally ½ hour before sunrise to sunset. September resident Canada goose and any Conservation Order hours differ.",
    overview: "Published Eastern and Western duck-zone dates, black-duck segments, Canada goose population zones, light geese, brant and youth/veteran/military days.",
    zones: ["Eastern Duck Zone", "Western Duck Zone", "Atlantic Population Goose Zone", "Late Southern Resident Goose Zone", "Late Western Resident Goose Zone", "Light Goose Eastern Zone", "Special Sea Duck Area"],
    seasons: [
      { name: "September Teal", dates: "Sept 17–26, 2026", open: false, zone: "Designated eastern counties and partial counties" },
      { name: "Regular Duck", dates: "Oct 10–17 • Nov 14–27 • Dec 15–Jan 30", open: false, zone: "Eastern Duck Zone" },
      { name: "Black Duck", dates: "Nov 14–27 • Dec 15–Jan 30", open: false, zone: "Eastern Duck Zone" },
      { name: "Regular Duck", dates: "Oct 3–17 • Nov 21–27 • Dec 15–Jan 30", open: false, zone: "Western Duck Zone" },
      { name: "Black Duck", dates: "Nov 21–27 • Dec 15–Jan 30", open: false, zone: "Western Duck Zone" },
      { name: "Youth / Veteran / Military Waterfowl", dates: "Nov 7, 2026 • Feb 6, 2027", open: false, zone: "Statewide" },
      { name: "Early Resident Canada Goose", dates: "Sept 1–15", open: false, zone: "Eastern Zone" },
      { name: "Early Resident Canada Goose", dates: "Sept 1–25", open: false, zone: "Western Zone" },
      { name: "Migratory Canada Goose", dates: "Nov 24–27 • Dec 15–Jan 30", open: false, zone: "Atlantic Population Goose Zone" },
      { name: "Late Resident Canada Goose", dates: "Nov 21–23 • Nov 24–27 • Dec 15–Jan 30 • Feb 1–Mar 10", open: false, zone: "Late Southern Resident Goose Zone" },
      { name: "Late Resident Canada Goose", dates: "Nov 21–27 • Dec 15–Mar 10", open: false, zone: "Late Western Resident Goose Zone" },
      { name: "Light Goose", dates: "Nov 7–27 • Nov 30–Feb 6 • Feb 8–Mar 10 eastern zone only", open: false, zone: "Statewide / Light Goose Eastern Zone" },
      { name: "Brant", dates: "Dec 28–Jan 30", open: false, zone: "Statewide" },
      { name: "Light Goose Conservation Order", dates: "To be determined in fall 2026", open: false, zone: "Designated eastern zone" },
    ],
    specialRules: [
      "Black ducks may be taken only during the separately listed black-duck season segments.",
      "Scaup limit is one per day, increasing to two from January 8–30.",
      "Sea ducks no longer have a separate season; they count in the six-duck bag during the regular duck season. Special Sea Duck Area retrieval and species restrictions still apply.",
      "Late Southern Resident Goose limit is five Nov. 21–23 and Feb. 1–Mar. 10, but two Nov. 24–27 and Dec. 15–Jan. 30.",
      "The Light Goose Conservation Order status, dates and limit remain to be determined in fall 2026.",
    ],
    birds: [...duckRules(3, 1),
      { id: "mottled-duck", label: "Mottled Duck", group: "Ducks", limit: 1 },
      { id: "fulvous-whistling", label: "Fulvous Whistling Duck", group: "Ducks", limit: 1 },
      { id: "early-canada-goose", label: "Early Resident Canada Goose", group: "Geese", limit: 8, note: "September season only." },
      { id: "canada-goose", label: "Canada / Cackling / White-fronted Goose", group: "Geese", limit: 2, zoneLimits: { "Atlantic Population Goose Zone": 2, "Late Southern Resident Goose Zone": 2, "Late Western Resident Goose Zone": 5 }, note: "Late Southern limit rises to five only during the listed November and February–March segments." },
      { id: "light-goose", label: "Snow / Ross’s Goose", group: "Geese", limit: 25 },
      { id: "brant", label: "Brant", group: "Geese", limit: 1 },
    ],
  },
  {
    code: "DE", name: "Delaware", seasonYear: "2026–2027 proposed package", dataStatus: "tentative",
    dataNotice: "DNREC published 2026–2027 proposals and bag-limit frameworks, but the final selected duck, youth and snow-goose options were not available in the reviewed online table. Proposal options are clearly labeled and must not be treated as final dates.",
    verifiedLabel: "Official DNREC proposals • final selections pending", officialUrl: "https://dnrec.delaware.gov/fish-wildlife/hunting/migratory-birds/proposed-seasons/",
    sourceLinks: [
      { label: "DNREC 2026–27 proposal page", url: "https://dnrec.delaware.gov/fish-wildlife/hunting/migratory-birds/proposed-seasons/" },
      { label: "DNREC proposal PDF", url: "https://documents.dnrec.delaware.gov/fw/Hunting/game-bird-proposals.pdf" },
      { label: "Delaware eRegulations guide", url: "https://www.eregulations.com/delaware/hunting/" },
    ],
    shootingHours: "Generally ½ hour before sunrise to sunset. September resident Canada goose and any Conservation Order hours differ.",
    overview: "DNREC proposal package includes four regular-duck date options plus fixed September teal, migratory Canada goose, tundra swan and brant proposals.",
    zones: ["Statewide Duck Zone", "Atlantic Population Canada Goose Zone", "Special September Teal Zone", "Special Sea Duck Area"],
    seasons: [
      { name: "September Teal — proposed", dates: "Sept 19–27", open: false, zone: "Special September Teal Zone" },
      { name: "Early Resident Canada Goose — proposed", dates: "Sept 1–25", open: false, zone: "Statewide; methods vary inside teal zone" },
      { name: "Regular Duck — proposal option 1", dates: "Oct 31–Nov 8 • Nov 25–29 • Dec 17–Jan 31", open: false, zone: "Statewide" },
      { name: "Regular Duck — proposal option 2", dates: "Oct 31–Nov 8 • Nov 23–29 • Dec 19–Jan 31", open: false, zone: "Statewide" },
      { name: "Regular Duck — proposal option 3", dates: "Oct 24–Nov 1 • Nov 23–29 • Dec 19–Jan 31", open: false, zone: "Statewide" },
      { name: "Regular Duck — proposal option 4", dates: "Oct 24–Nov 1 • Nov 25–29 • Dec 17–Jan 31", open: false, zone: "Statewide" },
      { name: "Migratory Canada Goose — proposed", dates: "Nov 25–29 • Dec 23–Jan 31", open: false, zone: "Atlantic Population Zone" },
      { name: "Tundra Swan — proposed", dates: "Nov 7–Jan 31", open: false, zone: "Special permit only" },
      { name: "Brant — proposed", dates: "Dec 19–Jan 2 • Jan 17–31", open: false, zone: "Statewide" },
      { name: "Snow Goose — proposed", dates: "Final option not selected in reviewed source", open: false, zone: "Statewide" },
    ],
    specialRules: [
      "Do not rely on the four duck options as final dates; DNREC must publish the selected option.",
      "Proposed duck bag is six with the listed species restrictions; scaup is one during the first 40 selected duck days and two during the last 20.",
      "Proposed youth/veteran/active-duty dates and the snow-goose/Conservation Order option remain unselected.",
      "Public wildlife areas may require permits, drawings or site-specific rules beyond the statewide package.",
    ],
    birds: [...duckRules(3, 1),
      { id: "mottled-duck", label: "Mottled Duck", group: "Ducks", limit: 1 },
      { id: "fulvous-whistling", label: "Fulvous Whistling Duck", group: "Ducks", limit: 1 },
      { id: "merganser", label: "Merganser", group: "Other", limit: 5 },
      { id: "early-canada-goose", label: "Early Resident Canada Goose", group: "Geese", limit: 15, note: "Proposed September season only." },
      { id: "canada-goose", label: "Canada / White-fronted Goose", group: "Geese", limit: 2, note: "Proposed migratory AP-zone limit." },
      { id: "snow-goose", label: "Snow / Ross’s Goose", group: "Geese", limit: 25, note: "Proposed regular-season limit; final option pending." },
      { id: "brant", label: "Brant", group: "Geese", limit: 1 },
      { id: "tundra-swan", label: "Tundra Swan", group: "Other", limit: 1, note: "One per season by special permit; proposed dates." },
    ],
  },
  {
    code: "VA", name: "Virginia", seasonYear: "2026–2027", dataStatus: "current",
    verifiedLabel: "2026–2027 • official Virginia DWR package", officialUrl: sources.VA,
    sourceLinks: [
      { label: "Virginia DWR migratory rules", url: sources.VA },
      { label: "2026–27 Virginia guide PDF", url: "https://dwr.virginia.gov/wp-content/uploads/media/2026-2027-Virginia-Hunting-Trapping-and-Migratory-Game-Bird-Seasons-Guide.pdf" },
    ],
    shootingHours: "Generally ½ hour before sunrise to sunset. September Canada goose and any Light Goose Conservation Order hours differ.",
    overview: "Official statewide duck dates, AP and Resident Population Canada goose zones, sea-duck retrieval area, light geese, brant and permit tundra swan rules.",
    zones: ["Statewide Duck Zone", "Atlantic Population Zone", "Resident Population Zone", "Special Sea Duck Area"],
    seasons: [
      { name: "September Teal", dates: "Sept 19–27", open: false, zone: "East of I-95" },
      { name: "September Teal", dates: "Sept 22–27", open: false, zone: "West of I-95" },
      { name: "Regular Duck / Coot / Merganser", dates: "Oct 9–12 • Nov 18–29 • Dec 19–Jan 31", open: false, zone: "Statewide" },
      { name: "Youth / Veteran Waterfowl", dates: "Oct 24, 2026 • Feb 6, 2027", open: false, zone: "Statewide" },
      { name: "September Canada Goose", dates: "Sept 1–25", open: false, zone: "Statewide" },
      { name: "Canada / White-fronted Goose", dates: "Nov 24–29 • Dec 24–Jan 31", open: false, zone: "Atlantic Population Zone" },
      { name: "Canada / White-fronted Goose", dates: "Nov 18–29 • Dec 19–Feb 21", open: false, zone: "Resident Population Zone" },
      { name: "Light Goose", dates: "Nov 25–Mar 10", open: false, zone: "Statewide" },
      { name: "Light Goose Conservation Order", dates: "Status determined September 2026", open: false, zone: "AP / Conservation Order Zone" },
      { name: "Atlantic Brant", dates: "Dec 19–31 • Jan 15–31", open: false, zone: "Statewide" },
      { name: "Tundra Swan", dates: "Nov 15–Jan 31", open: false, zone: "Permit hunt area" },
    ],
    specialRules: [
      "Black duck is closed during the October 9–12 duck segment.",
      "Scaup limit is one through January 11 and two January 12–31.",
      "The Special Sea Duck Area is now a retrieval area; sea ducks remain part of the regular six-duck bag.",
      "The 2027 Light Goose Conservation Order will be offered only if Virginia DWR confirms it in September 2026.",
      "Tundra swan requires a drawing permit and is limited to one per permittee per season.",
    ],
    birds: [...duckRules(3, 1),
      { id: "mottled-duck", label: "Mottled Duck", group: "Ducks", limit: 1 },
      { id: "fulvous-whistling", label: "Fulvous Whistling Duck", group: "Ducks", limit: 1 },
      { id: "merganser", label: "Merganser", group: "Other", limit: 5 },
      { id: "early-canada-goose", label: "September Canada Goose", group: "Geese", limit: 10, note: "September season only." },
      { id: "canada-goose", label: "Canada / White-fronted Goose", group: "Geese", limit: 2, zoneLimits: { "Atlantic Population Zone": 2, "Resident Population Zone": 5 } },
      { id: "light-goose", label: "Snow / Blue / Ross’s Goose", group: "Geese", limit: 25 },
      { id: "brant", label: "Atlantic Brant", group: "Geese", limit: 1 },
      { id: "tundra-swan", label: "Tundra Swan", group: "Other", limit: 1, note: "One per permittee per season; drawing permit required." },
    ],
  },
  {
    code: "NC", name: "North Carolina", seasonYear: "2026–2027", dataStatus: "current",
    verifiedLabel: "2026–2027 • official Wildlife Commission / eRegulations package", officialUrl: sources.NC,
    sourceLinks: [
      { label: "NC Wildlife hunting regulations", url: sources.NC },
      { label: "2026–27 eRegulations season table", url: "https://www.eregulations.com/northcarolina/hunting/migratory-game-bird-seasons" },
      { label: "Goose and duck zone map", url: "https://www.eregulations.com/northcarolina/hunting/goose-duck-zones-map" },
    ],
    shootingHours: "Generally ½ hour before sunrise to sunset. Migratory game bird hunting, including waterfowl, is prohibited on Sundays.",
    overview: "Separate Inland and Coastal duck zones, resident and northeast Canada goose zones, permit tundra swan, light geese and statewide youth/veteran/military days.",
    zones: ["Inland Duck Zone", "Coastal Duck Zone", "Resident Population Goose Zone", "Northeast Hunt Zone", "Sea Duck Area"],
    seasons: [
      { name: "September Teal", dates: "Sept 10–19", open: false, zone: "East of U.S. Highway 17" },
      { name: "Regular Duck", dates: "Oct 15–17 • Nov 7–28 • Dec 18–Jan 30", open: false, zone: "Inland Duck Zone" },
      { name: "Regular Duck", dates: "Oct 23–24 • Nov 7–28 • Dec 17–Jan 30", open: false, zone: "Coastal Duck Zone" },
      { name: "Sea Ducks", dates: "Oct 23–24 • Nov 7–28 • Dec 17–Jan 30", open: false, zone: "Sea Duck Area" },
      { name: "Youth / Veteran / Military Waterfowl", dates: "Dec 5, 2026 • Feb 6, 2027", open: false, zone: "Statewide" },
      { name: "September Canada Goose", dates: "Sept 1–30", open: false, zone: "Statewide" },
      { name: "Canada / White-fronted Goose", dates: "Oct 15–24 • Nov 7–Dec 5 • Dec 17–Feb 6", open: false, zone: "Resident Population Goose Zone" },
      { name: "Canada / White-fronted Goose", dates: "Dec 28–Jan 30", open: false, zone: "Northeast Hunt Zone" },
      { name: "Tundra Swan", dates: "Nov 7–Jan 30", open: false, zone: "Special permit only" },
      { name: "Light Goose", dates: "Nov 7–Mar 10", open: false, zone: "Statewide" },
      { name: "Light Goose Conservation Order", dates: "Status determined fall 2026", open: false, zone: "By permit if offered" },
      { name: "Brant", dates: "Dec 28–Jan 30", open: false, zone: "Statewide" },
    ],
    specialRules: [
      "No Sunday hunting for migratory game birds, including waterfowl.",
      "Black and mottled ducks are closed until November 21.",
      "Scaup limit is one before January 8 and two beginning January 8.",
      "All sea ducks count toward the general six-duck daily bag; Sea Duck Area retrieval rules apply.",
      "The 2027 Light Goose Conservation Order will be determined in fall 2026.",
      "Tundra swan harvest is limited to one per season and requires a special drawing permit.",
    ],
    birds: [...duckRules(3, 1),
      { id: "mottled-duck", label: "Mottled Duck", group: "Ducks", limit: 1, note: "Closed until November 21." },
      { id: "fulvous-whistling", label: "Fulvous Whistling Duck", group: "Ducks", limit: 1 },
      { id: "hooded-merganser", label: "Hooded Merganser", group: "Other", limit: 2, parent: "merganser", parentLimit: 5 },
      { id: "other-merganser", label: "Other Merganser", group: "Other", limit: 5, parent: "merganser", parentLimit: 5 },
      { id: "early-canada-goose", label: "September Canada Goose", group: "Geese", limit: 15, note: "September season only." },
      { id: "canada-goose", label: "Canada / White-fronted Goose", group: "Geese", limit: 5, zoneLimits: { "Resident Population Goose Zone": 5, "Northeast Hunt Zone": 2 } },
      { id: "light-goose", label: "Snow / Ross’s Goose", group: "Geese", limit: 25 },
      { id: "brant", label: "Brant", group: "Geese", limit: 1 },
      { id: "tundra-swan", label: "Tundra Swan", group: "Other", limit: 1, note: "One per season by special permit." },
    ],
  },
  {
    code: "PA", name: "Pennsylvania", seasonYear: "2026–2027", dataStatus: "current",
    verifiedLabel: "2026–2027 • official PGC season package", officialUrl: sources.PA,
    shootingHours: "Generally ½ hour before sunrise to sunset. Migratory game bird hunting is closed on Sundays.",
    overview: "Four duck zones, two Canada goose population zones, zone- and date-specific scaup rules, and no Sunday migratory-bird hunting.",
    zones: ["North Duck Zone", "South Duck Zone", "Northwest Duck Zone", "Lake Erie Duck Zone", "Resident Population Goose Zone", "Atlantic Population Goose Zone"],
    seasons: [
      { name: "Ducks, sea ducks, coots & mergansers", dates: "Oct 10–24 • Nov 17–Jan 9", open: false, zone: "North Duck Zone" },
      { name: "Ducks, sea ducks, coots & mergansers", dates: "Oct 10–17 • Nov 18–Jan 18", open: false, zone: "South Duck Zone" },
      { name: "Ducks, sea ducks, coots & mergansers", dates: "Oct 10–Nov 27 • Dec 21–Jan 9", open: false, zone: "Northwest Duck Zone" },
      { name: "Ducks, sea ducks, coots & mergansers", dates: "Nov 2–Jan 9", open: false, zone: "Lake Erie Duck Zone" },
      { name: "Canada Goose — Regular", dates: "Oct 24–Nov 27 • Dec 15–Jan 18 • Jan 29–Feb 20", open: false, zone: "Resident Population Goose Zone" },
      { name: "Canada Goose — Regular", dates: "Nov 21–27 • Dec 4–Jan 18", open: false, zone: "Atlantic Population Goose Zone" },
      { name: "Light Geese", dates: "Nov 6–Mar 10", open: false, zone: "All goose zones" },
      { name: "Brant", dates: "Oct 10–Nov 13", open: false, zone: "All zones" },
    ],
    birds: [...duckRules(3),
      { id: "merganser", label: "Merganser", group: "Ducks", limit: 5 },
      { id: "canada-goose", label: "Canada / White-fronted Goose", group: "Geese", limit: 3, zoneLimits: { "Resident Population Goose Zone": 5, "Atlantic Population Goose Zone": 3 }, note: "Regular-season limit; September and special-segment limits differ." },
      { id: "light-goose", label: "Snow / Ross’s Goose", group: "Geese", limit: 25 },
      { id: "brant", label: "Brant", group: "Geese", limit: 1 },
    ],
  },
  {
    code: "NY", name: "New York", seasonYear: "2026–2027", dataStatus: "current",
    verifiedLabel: "2026–2027 • official NYSDEC season package", officialUrl: sources.NY,
    shootingHours: "Generally ½ hour before sunrise to sunset. September Canada goose exceptions apply.",
    overview: "Five duck zones and nine Canada goose areas with separate season segments, limits, youth days and military days.",
    zones: ["Western Waterfowl Zone", "Northeast Waterfowl Zone", "Lake Champlain Waterfowl Zone", "Southeast Waterfowl Zone", "Long Island Waterfowl Zone", "Northeast Goose Area", "West Central Goose Area", "East Central Goose Area", "Hudson Valley Goose Area", "Lake Champlain Goose Area", "South Goose Area", "Western Long Island Goose Area", "Central Long Island Goose Area", "Eastern Long Island Goose Area"],
    seasons: [
      { name: "Ducks, coots & mergansers", dates: "Oct 10–Nov 1 • Dec 5–Jan 10", open: false, zone: "Western Waterfowl Zone" },
      { name: "Ducks, coots & mergansers", dates: "Oct 10–Nov 29 • Dec 12–20", open: false, zone: "Northeast Waterfowl Zone" },
      { name: "Ducks, coots & mergansers", dates: "Oct 10–Nov 1 • Nov 21–Dec 27", open: false, zone: "Lake Champlain Waterfowl Zone" },
      { name: "Ducks, coots & mergansers", dates: "Oct 10–18 • Nov 7–Dec 27", open: false, zone: "Southeast Waterfowl Zone" },
      { name: "Ducks, coots & mergansers", dates: "Nov 21–29 • Dec 12–Jan 31", open: false, zone: "Long Island Waterfowl Zone" },
      { name: "Canada Goose", dates: "Dates and limits vary across nine goose areas", open: false, zone: "Select a goose area" },
      { name: "Snow Goose", dates: "Zone-specific dates through Mar 10", open: false, zone: "Select waterfowl zone" },
      { name: "Brant", dates: "Oct 10–Nov 8; Long Island Jan 2–31", open: false, zone: "Zone-specific" },
    ],
    birds: [...duckRules(3),
      { id: "merganser", label: "Merganser", group: "Ducks", limit: 6, note: "Included in New York's aggregate six-bird duck bag." },
      { id: "canada-goose", label: "Canada / White-fronted Goose", group: "Geese", limit: 3, zoneLimits: { "Northeast Goose Area": 3, "West Central Goose Area": 3, "East Central Goose Area": 3, "Hudson Valley Goose Area": 3, "Lake Champlain Goose Area": 3, "South Goose Area": 5, "Western Long Island Goose Area": 8, "Central Long Island Goose Area": 3, "Eastern Long Island Goose Area": 2 }, note: "Regular-season limit; September and special-season limits differ." },
      { id: "snow-goose", label: "Snow / Ross’s Goose", group: "Geese", limit: 25 },
      { id: "brant", label: "Brant", group: "Geese", limit: 1 },
    ],
  },
  {
    code: "WV", name: "West Virginia", seasonYear: "2025–2026 reference", dataStatus: "archived",
    dataNotice: "WVDNR announced that its 2026–2027 migratory-bird regulations are available, but the agency regulations page still linked the 2025–2026 waterfowl PDF during BlindIQ’s August 11 review. The expired dates below remain locked until the current waterfowl table is retrievable and verified.",
    verifiedLabel: "WVDNR 2026–27 release announced • waterfowl table retrieval pending", officialUrl: sources.WV,
    sourceLinks: [
      { label: "WVDNR 2026–27 release notice", url: sources.WV },
      { label: "WVDNR regulations downloads", url: "https://wvdnr.gov/hunting/hunting-regulations/" },
    ],
    shootingHours: "Generally ½ hour before sunrise to sunset; WMA and concurrent-season restrictions apply.",
    overview: "Archived statewide waterfowl package retained for comparison only. Live hunt logging stays disabled until the current WVDNR waterfowl table is obtained.",
    zones: ["Statewide"],
    seasons: [
      { name: "Youth Waterfowl", dates: "Sept 20 • Nov 1, 2025", open: false, zone: "Statewide — archived" },
      { name: "Regular Duck", dates: "Oct 4–12 • Nov 8–16 • Dec 21–Jan 31", open: false, zone: "Statewide — 2025–2026" },
      { name: "Canada / White-fronted Goose", dates: "Oct 4–19 • Nov 8–16 • Dec 8–Jan 31", open: false, zone: "Statewide — 2025–2026" },
      { name: "Early Canada Goose", dates: "Sept 1–14, 2025", open: false, zone: "Statewide — archived" },
      { name: "Snow / Blue Goose", dates: "Oct 4–19 • Nov 8–16 • Dec 8–Jan 31", open: false, zone: "Statewide — 2025–2026" },
      { name: "Brant", dates: "Jan 2–31, 2026", open: false, zone: "Statewide — archived" },
    ],
    birds: [...duckRules(3),
      { id: "merganser", label: "Merganser", group: "Ducks", limit: 5 },
      { id: "canada-goose", label: "Canada / White-fronted Goose", group: "Geese", limit: 5 },
      { id: "snow-goose", label: "Snow / Blue Goose", group: "Geese", limit: 5 },
      { id: "brant", label: "Brant", group: "Geese", limit: 1 },
    ],
  },
  {
    code: "SC", name: "South Carolina", seasonYear: "2026–2027", dataStatus: "current",
    verifiedLabel: "2026–2027 • SCDNR / eRegulations guide package", officialUrl: sources.SC,
    sourceLinks: [
      { label: "2026–27 South Carolina guide PDF", url: sources.SC },
      { label: "South Carolina eRegulations hub", url: "https://www.eregulations.com/southcarolina/hunting/" },
      { label: "SCDNR hunting information", url: "https://www.dnr.sc.gov/hunting.html" },
    ],
    shootingHours: "Generally ½ hour before sunrise to sunset. Early teal runs sunrise to sunset; special-area rules apply.",
    overview: "Official statewide dates with early teal, date-dependent scaup, I-95 black/mottled-duck aggregates, separate merganser bag and late goose segments.",
    zones: ["Statewide", "East and South of I-95", "West and North of I-95", "Sea Duck Area"],
    seasons: [
      { name: "Early Teal", dates: "Sept 19–27, 2026", open: false, zone: "Statewide" },
      { name: "Regular Duck / Sea Duck / Coot", dates: "Nov 21–28 • Dec 12–Jan 31", open: false, zone: "Statewide" },
      { name: "State Youth Waterfowl", dates: "Nov 14, 2026", open: false, zone: "Statewide" },
      { name: "Federal Youth / Veteran / Active Duty", dates: "Feb 6 • Feb 13, 2027", open: false, zone: "Statewide" },
      { name: "Early Canada Goose", dates: "Sept 1–30, 2026", open: false, zone: "Statewide" },
      { name: "Canada Goose", dates: "Nov 21–28 • Dec 12–Jan 31 • Feb 15–Mar 1", open: false, zone: "Statewide" },
      { name: "White-fronted & Snow Goose", dates: "Nov 21–28 • Dec 12–Jan 31 • Feb 15–Mar 1", open: false, zone: "Statewide" },
      { name: "Brant", dates: "Jan 2–31, 2027", open: false, zone: "Statewide" },
    ],
    specialRules: [
      "Scaup limit is two Nov. 21–28 and Dec. 12–22; it is one Dec. 23–Jan. 31. The special November 14 and February 6/13 hunt-day limit is two.",
      "East and south of I-95: one black duck or one mottled duck total. West and north of I-95: two black ducks, or one black duck and one mottled duck total.",
      "The six-duck bag may include no more than five black-bellied whistling ducks and one fulvous whistling duck.",
      "Mergansers have a separate five-bird bag with no more than one hooded merganser.",
      "The Sea Duck Area permits shooting crippled waterfowl from a vessel under motor power; sea ducks still count in the regular duck bag.",
    ],
    birds: [
      { id: "mallard-drake", label: "Mallard — Drake", group: "Ducks", limit: 4, sex: "Drake", parent: "mallard", parentLimit: 4 },
      { id: "mallard-hen", label: "Mallard — Hen", group: "Ducks", limit: 2, sex: "Hen", parent: "mallard", parentLimit: 4 },
      { id: "wood-duck", label: "Wood Duck", group: "Ducks", limit: 3 },
      { id: "pintail", label: "Northern Pintail", group: "Ducks", limit: 3 },
      { id: "redhead", label: "Redhead", group: "Ducks", limit: 2 },
      { id: "canvasback", label: "Canvasback", group: "Ducks", limit: 2 },
      { id: "scaup", label: "Scaup", group: "Ducks", limit: 1, note: "Conservative live-logger value; limit is two during the listed early segments and special hunt days." },
      { id: "black-duck", label: "American Black Duck", group: "Ducks", limit: 2, zoneLimits: { "East and South of I-95": 1, "West and North of I-95": 2 }, parent: "black-mottled", parentLimits: { "East and South of I-95": 1, "West and North of I-95": 2 } },
      { id: "mottled-duck", label: "Mottled Duck", group: "Ducks", limit: 1, parent: "black-mottled", parentLimits: { "East and South of I-95": 1, "West and North of I-95": 2 } },
      { id: "black-bellied-whistling", label: "Black-bellied Whistling Duck", group: "Ducks", limit: 5 },
      { id: "fulvous-whistling", label: "Fulvous Whistling Duck", group: "Ducks", limit: 1 },
      { id: "sea-duck", label: "Sea Duck", group: "Ducks", limit: 4, note: "No more than three each of scoters, long-tailed ducks or eiders; only one hen eider." },
      { id: "other-duck", label: "Other legal duck", group: "Ducks", limit: 6 },
      { id: "hooded-merganser", label: "Hooded Merganser", group: "Other", limit: 1, parent: "merganser", parentLimit: 5 },
      { id: "other-merganser", label: "Other Merganser", group: "Other", limit: 5, parent: "merganser", parentLimit: 5 },
      { id: "coot", label: "Coot", group: "Other", limit: 15 },
      { id: "early-canada-goose", label: "September Canada Goose", group: "Geese", limit: 15, note: "September season only." },
      { id: "canada-goose", label: "Canada Goose", group: "Geese", limit: 5, parent: "dark-goose", parentLimit: 5 },
      { id: "white-fronted-goose", label: "White-fronted Goose", group: "Geese", limit: 2, parent: "dark-goose", parentLimit: 5 },
      { id: "snow-goose", label: "Snow Goose", group: "Geese", limit: 25 },
      { id: "brant", label: "Brant", group: "Geese", limit: 1 },
    ],
  },
  {
    code: "LA", name: "Louisiana", seasonYear: "2026–2027", dataStatus: "current",
    verifiedLabel: "2026–2027 • official LDWF migratory-bird package", officialUrl: sources.LA,
    shootingHours: "Generally ½ hour before sunrise to sunset. Early teal begins at sunrise; Conservation Order hours extend to ½ hour after sunset.",
    overview: "East and West waterfowl zones with date-dependent scaup and mottled-duck rules, plus a separate permitted black-bellied whistling-duck season.",
    zones: ["East Waterfowl Zone", "West Waterfowl Zone"],
    seasons: [
      { name: "Early Teal", dates: "Sept 19–27, 2026", open: false, zone: "Statewide" },
      { name: "Black-bellied Whistling Duck", dates: "Oct 3–11, 2026", open: false, zone: "Statewide — free permit required" },
      { name: "Regular Duck", dates: "Nov 21–Dec 6 • Dec 19–Jan 31", open: false, zone: "East Waterfowl Zone" },
      { name: "Regular Duck", dates: "Nov 14–Dec 6 • Dec 19–Jan 24", open: false, zone: "West Waterfowl Zone" },
      { name: "Dark & Light Geese", dates: "Nov 14–Dec 6 • Dec 19–Feb 7", open: false, zone: "East & West Zones" },
      { name: "Light Goose Conservation Order", dates: "Dec 7–18 • Feb 8–Mar 7", open: false, zone: "East & West Zones" },
    ],
    specialRules: [
      "Only one scaup may be taken during the first 15 days of each zone's regular season; two are allowed afterward.",
      "Mottled ducks are closed during the first 15 days of each zone's regular season; one is allowed afterward.",
      "The three-pintail limit may include no more than one female pintail.",
      "A free LDWF Black-bellied Whistling Duck Permit is required for the October 3–11 season.",
      "Light Goose Conservation Order permits electronic calls, unplugged shotguns and has no daily or possession limit.",
    ],
    birds: [
      { id: "mallard-drake", label: "Mallard — Drake", group: "Ducks", limit: 4, sex: "Drake", parent: "mallard", parentLimit: 4 },
      { id: "mallard-hen", label: "Mallard — Hen", group: "Ducks", limit: 2, sex: "Hen", parent: "mallard", parentLimit: 4 },
      { id: "wood-duck", label: "Wood Duck", group: "Ducks", limit: 3 },
      { id: "pintail-drake", label: "Northern Pintail — Drake", group: "Ducks", limit: 3, sex: "Drake", parent: "pintail", parentLimit: 3 },
      { id: "pintail-hen", label: "Northern Pintail — Hen", group: "Ducks", limit: 1, sex: "Hen", parent: "pintail", parentLimit: 3 },
      { id: "black-duck", label: "American Black Duck", group: "Ducks", limit: 1 },
      { id: "mottled-duck", label: "Mottled Duck", group: "Ducks", limit: 1, note: "Closed for the first 15 days of regular season." },
      { id: "redhead", label: "Redhead", group: "Ducks", limit: 2 },
      { id: "canvasback", label: "Canvasback", group: "Ducks", limit: 2 },
      { id: "scaup", label: "Scaup", group: "Ducks", limit: 1, note: "One during the first 15 days; two afterward." },
      { id: "other-duck", label: "Other legal duck", group: "Ducks", limit: 6 },
      { id: "black-bellied-whistling", label: "Black-bellied Whistling Duck", group: "Ducks", limit: 4, note: "Separate October season and free permit required." },
      { id: "merganser", label: "Merganser", group: "Ducks", limit: 5, note: "No more than two hooded mergansers." },
      { id: "coot", label: "Coot", group: "Other", limit: 15 },
      { id: "canada-goose", label: "Canada Goose", group: "Geese", limit: 1 },
      { id: "white-fronted-goose", label: "White-fronted Goose", group: "Geese", limit: 3 },
      { id: "light-goose", label: "Snow / Blue / Ross’s Goose", group: "Geese", limit: 20 },
    ],
  },
  {
    code: "TX", name: "Texas", seasonYear: "2026–2027", dataStatus: "current",
    verifiedLabel: "2026–2027 • official TPWD Outdoor Annual", officialUrl: sources.TX,
    shootingHours: "Generally ½ hour before sunrise to sunset. County and special-season exceptions may apply.",
    overview: "Three duck zones and two goose zones. County selection ultimately determines the correct zone; dusky ducks are closed for each zone's first five regular-season days.",
    zones: ["High Plains Mallard Management Unit", "North Duck Zone", "South Duck Zone", "Eastern Goose Zone", "Western Goose Zone"],
    seasons: [
      { name: "Early Teal", dates: "Sept 19–27, 2026", open: false, zone: "Statewide" },
      { name: "Regular Duck", dates: "Oct 24–25 • Oct 30–Jan 31", open: false, zone: "High Plains Mallard Management Unit" },
      { name: "Regular Duck", dates: "Nov 14–29 • Dec 5–Jan 31", open: false, zone: "North Duck Zone" },
      { name: "Regular Duck", dates: "Nov 7–29 • Dec 12–Jan 31", open: false, zone: "South Duck Zone" },
      { name: "Early Canada Goose", dates: "Sept 12–27", open: false, zone: "Eastern Goose Zone" },
      { name: "Dark Geese", dates: "Nov 7–Jan 31", open: false, zone: "Eastern Goose Zone" },
      { name: "Dark Geese", dates: "Nov 7–Feb 7", open: false, zone: "Western Goose Zone" },
      { name: "Light Geese", dates: "Nov 7–Feb 19 East • Nov 7–Feb 7 West", open: false, zone: "Select goose zone" },
    ],
    specialRules: [
      "Dusky ducks—mottled, Mexican, black ducks and their hybrids—are closed during the first five days of regular duck season in each zone.",
      "Texas regulations are county-based; verify that the selected zone matches the county where the hunt occurs.",
      "The aggregate duck limit includes mergansers.",
      "Migratory Game Bird Endorsement, HIP certification and Federal Duck Stamp requirements apply.",
    ],
    birds: [
      { id: "mallard-drake", label: "Mallard — Drake", group: "Ducks", limit: 5, sex: "Drake", parent: "mallard", parentLimit: 5 },
      { id: "mallard-hen", label: "Mallard — Hen", group: "Ducks", limit: 2, sex: "Hen", parent: "mallard", parentLimit: 5 },
      { id: "wood-duck", label: "Wood Duck", group: "Ducks", limit: 3 },
      { id: "pintail", label: "Northern Pintail", group: "Ducks", limit: 3 },
      { id: "redhead", label: "Redhead", group: "Ducks", limit: 2 },
      { id: "canvasback", label: "Canvasback", group: "Ducks", limit: 2 },
      { id: "scaup", label: "Scaup", group: "Ducks", limit: 1 },
      { id: "dusky-duck", label: "Dusky Duck", group: "Ducks", limit: 1, note: "Closed during the first five regular-season days in each zone." },
      { id: "merganser", label: "Merganser", group: "Ducks", limit: 6, note: "Included in the aggregate six-duck limit." },
      { id: "other-duck", label: "Other legal duck", group: "Ducks", limit: 6 },
      { id: "coot", label: "Coot", group: "Other", limit: 15 },
      { id: "dark-goose", label: "Dark Goose", group: "Geese", limit: 5, note: "Eastern Zone may include no more than two white-fronted geese." },
      { id: "light-goose", label: "Light Goose", group: "Geese", limit: 5 },
    ],
  },
  {
    code: "AR", name: "Arkansas", seasonYear: "2026–2027", dataStatus: "current",
    verifiedLabel: "2026–2027 • official AGFC waterfowl package", officialUrl: sources.AR,
    shootingHours: "Generally 30 minutes before sunrise to sunset; most WMAs close regular waterfowl hunting at noon and impose departure deadlines.",
    overview: "Statewide waterfowl seasons with extensive WMA-specific permits, access restrictions, noon closures and departure-time requirements.",
    zones: ["Statewide", "AGFC Wildlife Management Area"],
    seasons: [
      { name: "Early Teal", dates: "Sept 19–27, 2026", open: false, zone: "Statewide" },
      { name: "Duck, Coot & Merganser", dates: "Nov 21–29 • Dec 10–23 • Dec 26–Jan 31", open: false, zone: "Statewide" },
      { name: "Youth, Veteran & Military", dates: "Feb 6–7, 2027", open: false, zone: "Statewide" },
      { name: "Early Canada Goose", dates: "Sept 1–Oct 15", open: false, zone: "Statewide" },
      { name: "Regular Canada Goose", dates: "Nov 21–29 • Dec 10–23 • Dec 26–Jan 31", open: false, zone: "Statewide" },
      { name: "White-fronted & Light Geese", dates: "Oct 31–Nov 8 • Nov 21–29 • Dec 10–23 • Dec 26–Jan 31", open: false, zone: "Statewide" },
      { name: "Light Goose Conservation Order", dates: "Feb 1–5 • Feb 8–Apr 25", open: false, zone: "Statewide" },
    ],
    specialRules: [
      "Most AGFC WMAs end regular waterfowl shooting at noon, with separate deadlines for leaving water-inundated areas.",
      "WMA-specific permit, boat, access and nonresident restrictions must be checked before hunting.",
      "Early Canada goose limit is five; the regular-season Canada goose limit is two.",
      "A valid Arkansas hunting license and state duck stamp are required for the Light Goose Conservation Order.",
      "Federally approved nontoxic shot is required for ducks, geese and mergansers statewide.",
    ],
    birds: [
      ...duckRules(3),
      { id: "mottled-duck", label: "Mottled Duck", group: "Ducks", limit: 1 },
      { id: "merganser", label: "Merganser", group: "Ducks", limit: 5, note: "No more than two hooded mergansers." },
      { id: "canada-goose", label: "Canada Goose", group: "Geese", limit: 2, note: "Regular season; early-season limit is five." },
      { id: "white-fronted-goose", label: "White-fronted Goose", group: "Geese", limit: 2 },
      { id: "light-goose", label: "Snow / Blue / Ross’s Goose", group: "Geese", limit: 20 },
    ],
  },
  {
    code: "ND", name: "North Dakota", seasonYear: "2026–2027", dataStatus: "current",
    verifiedLabel: "2026–2027 • official NDGF proclamation", officialUrl: sources.ND,
    shootingHours: "Ducks: generally ½ hour before sunrise to sunset. Regular goose hours often end at 2 p.m. until expanded on specified days and later in the season.",
    overview: "High and Low Plains duck units, three Canada goose zones, resident/nonresident opening differences, nonresident license zones and a bonus blue-winged teal period.",
    zones: ["Low Plains Duck Unit", "High Plains Duck Unit", "Missouri River Canada Goose Zone", "Western Canada Goose Zone", "Eastern Canada Goose Zone"],
    seasons: [
      { name: "Youth, Veteran & Military Waterfowl", dates: "Sept 19–20, 2026", open: false, zone: "Statewide" },
      { name: "Resident Duck", dates: "Sept 26–Dec 6", open: false, zone: "Low Plains Duck Unit" },
      { name: "Resident Duck", dates: "Sept 26–Dec 6 • Dec 12–Jan 3", open: false, zone: "High Plains Duck Unit" },
      { name: "Nonresident Duck", dates: "Begins Oct 5; licensed zone restrictions apply", open: false, zone: "Selected nonresident license zone" },
      { name: "Bonus Blue-winged Teal", dates: "Sept 26–Oct 4", open: false, zone: "All duck units" },
      { name: "Early Canada Goose", dates: "Aug 15–Sept 7 Missouri River • Aug 15–Sept 15 West • Aug 15–Sept 22 East", open: false, zone: "Select goose zone" },
      { name: "Regular Canada Goose", dates: "Sept 26–Jan 1 Missouri River • through Dec 24 West • through Dec 19 East", open: false, zone: "Select goose zone" },
      { name: "White-fronted Goose", dates: "Sept 26–Dec 6", open: false, zone: "Statewide" },
      { name: "Light Goose", dates: "Sept 26–Jan 3", open: false, zone: "Statewide" },
    ],
    specialRules: [
      "Residents begin regular waterfowl hunting September 26; nonresidents begin October 5 and must remain within the zone selected for their license.",
      "Two bonus blue-winged teal may be taken in addition to the regular six-duck limit from September 26 through October 4.",
      "Regular goose shooting generally closes at 2 p.m.; specified Wednesdays and Saturdays have sunset closure through November 28, and all days extend to sunset beginning November 29.",
      "A motorized floating craft must be at rest with its motor turned off before migratory game birds may be taken.",
      "Electronic or recorded calls are prohibited for waterfowl during regular seasons.",
    ],
    birds: [
      { id: "mallard-drake", label: "Mallard — Drake", group: "Ducks", limit: 5, sex: "Drake", parent: "mallard", parentLimit: 5 },
      { id: "mallard-hen", label: "Mallard — Hen", group: "Ducks", limit: 2, sex: "Hen", parent: "mallard", parentLimit: 5 },
      { id: "wood-duck", label: "Wood Duck", group: "Ducks", limit: 3 },
      { id: "pintail", label: "Northern Pintail", group: "Ducks", limit: 3 },
      { id: "redhead", label: "Redhead", group: "Ducks", limit: 2 },
      { id: "canvasback", label: "Canvasback", group: "Ducks", limit: 2 },
      { id: "scaup", label: "Scaup", group: "Ducks", limit: 1 },
      { id: "other-duck", label: "Other legal duck", group: "Ducks", limit: 6 },
      { id: "bonus-bluewing-teal", label: "Bonus Blue-winged Teal", group: "Other", limit: 2, note: "Additional to the six-duck bag only Sept 26–Oct 4." },
      { id: "coot", label: "Coot", group: "Other", limit: 15 },
      { id: "canada-goose", label: "Canada Goose", group: "Geese", limit: 5, zoneLimits: { "Missouri River Canada Goose Zone": 5, "Western Canada Goose Zone": 8, "Eastern Canada Goose Zone": 8 }, note: "Regular-season limits. Early-season limit is 15 in all three zones." },
      { id: "white-fronted-goose", label: "White-fronted Goose", group: "Geese", limit: 3 },
      { id: "light-goose", label: "Light Goose", group: "Geese", limit: 50 },
    ],
  },
  {
    code: "WI", name: "Wisconsin", seasonYear: "2026–2027", dataStatus: "current",
    verifiedLabel: "2026–2027 • official Wisconsin DNR package", officialUrl: sources.WI,
    shootingHours: "Generally ½ hour before sunrise to sunset. Early teal shooting begins at sunrise; location-specific tables and exceptions apply.",
    overview: "Three duck zones and three Canada goose zones with split southern seasons, date-dependent scaup limits and a holiday Canada goose limit change.",
    zones: ["Northern Duck Zone", "Southern Duck Zone", "Open Water Duck Zone", "Northern Goose Zone", "Southern Goose Zone", "Mississippi River Goose Zone"],
    seasons: [
      { name: "Early Teal", dates: "Sept 1–9, 2026", open: false, zone: "Statewide" },
      { name: "Early Goose", dates: "Sept 1–15, 2026", open: false, zone: "Statewide" },
      { name: "Youth Waterfowl", dates: "Sept 19–20, 2026", open: false, zone: "Statewide" },
      { name: "Regular Duck", dates: "Sept 26–Nov 24", open: false, zone: "Northern Duck Zone" },
      { name: "Regular Duck", dates: "Oct 3–11 • Oct 17–Dec 6", open: false, zone: "Southern Duck Zone" },
      { name: "Regular Duck", dates: "Oct 17–Dec 15", open: false, zone: "Open Water Duck Zone" },
      { name: "Regular Goose", dates: "Sept 16–Dec 16", open: false, zone: "Northern Goose Zone" },
      { name: "Regular Goose", dates: "Sept 16–Oct 11 • Oct 17–Dec 6 • Dec 19–Jan 2", open: false, zone: "Southern Goose Zone" },
      { name: "Regular Goose", dates: "Oct 3–11 • Oct 17–Jan 5", open: false, zone: "Mississippi River Goose Zone" },
    ],
    specialRules: [
      "Scaup: Northern Zone allows two through November 9, then one; Southern Zone allows one through October 22, then two; Open Water Zone allows two through November 30, then one.",
      "The Southern Goose Zone Canada goose limit increases from three to five only during the December 19–January 2 holiday segment.",
      "A Wisconsin Canada Goose Permit is required for both the early and regular Canada goose seasons.",
      "Duck and goose zone boundaries must be checked separately; U.S. Highways 10 and 41 divide the northern and southern zones.",
      "HIP registration, state and federal waterfowl stamps, and approved nontoxic shot requirements apply as specified by Wisconsin DNR.",
    ],
    birds: [
      { id: "mallard-drake", label: "Mallard — Drake", group: "Ducks", limit: 4, sex: "Drake", parent: "mallard", parentLimit: 4 },
      { id: "mallard-hen", label: "Mallard — Hen", group: "Ducks", limit: 2, sex: "Hen", parent: "mallard", parentLimit: 4 },
      { id: "black-duck", label: "American Black Duck", group: "Ducks", limit: 2 },
      { id: "wood-duck", label: "Wood Duck", group: "Ducks", limit: 3 },
      { id: "pintail", label: "Northern Pintail", group: "Ducks", limit: 3 },
      { id: "redhead", label: "Redhead", group: "Ducks", limit: 2 },
      { id: "canvasback", label: "Canvasback", group: "Ducks", limit: 2 },
      { id: "scaup", label: "Scaup", group: "Ducks", limit: 2, note: "The one- or two-bird limit changes by duck zone and date; see the loaded restrictions." },
      { id: "other-duck", label: "Other legal duck", group: "Ducks", limit: 6 },
      { id: "hooded-merganser", label: "Hooded Merganser", group: "Other", limit: 2, parent: "merganser", parentLimit: 5, note: "Mergansers have a separate five-bird aggregate limit." },
      { id: "other-merganser", label: "Other Merganser", group: "Other", limit: 5, parent: "merganser", parentLimit: 5 },
      { id: "coot", label: "Coot", group: "Other", limit: 15 },
      { id: "canada-goose", label: "Canada Goose", group: "Geese", limit: 3, note: "Regular limit; Southern Zone holiday segment allows five. Early-season limit is five." },
      { id: "white-fronted-goose", label: "Greater White-fronted Goose", group: "Geese", limit: 1 },
      { id: "light-goose", label: "Snow / Blue / Ross’s Goose", group: "Geese", limit: 20 },
      { id: "brant", label: "Brant", group: "Geese", limit: 1 },
    ],
  },
  {
    code: "IL", name: "Illinois", seasonYear: "2026–2027 preseason", dataStatus: "tentative",
    dataNotice: "Illinois’s 2026–2030 zone structure and 2026–2027 season dates are official. The species limits in the hunt logger are preseason working values until IDNR publishes its final 2026–2027 hunting digest; verify every limit before hunting.",
    verifiedLabel: "Official 2026–2027 dates • final IDNR limits pending", officialUrl: sources.IL,
    shootingHours: "Generally ½ hour before sunrise to sunset. September teal begins at sunrise; site-specific public-land hours and rules may be more restrictive.",
    overview: "A new three-zone system begins in 2026, combining the former South-Central and South zones and adding split duck seasons in every zone.",
    zones: ["North Waterfowl Zone", "Central Waterfowl Zone", "South Waterfowl Zone"],
    seasons: [
      { name: "Early Teal", dates: "Sept 5–13, 2026", open: false, zone: "Statewide" },
      { name: "Youth Waterfowl", dates: "Oct 17–18", open: false, zone: "North Waterfowl Zone" },
      { name: "Youth Waterfowl", dates: "Oct 24–25", open: false, zone: "Central Waterfowl Zone" },
      { name: "Youth Waterfowl", dates: "Nov 7 • Jan 30", open: false, zone: "South Waterfowl Zone" },
      { name: "Regular Duck", dates: "Oct 24–25 • Oct 31–Dec 27", open: false, zone: "North Waterfowl Zone" },
      { name: "Regular Duck", dates: "Oct 31–Dec 13 • Dec 19–Jan 3", open: false, zone: "Central Waterfowl Zone" },
      { name: "Regular Duck", dates: "Nov 14–Dec 6 • Dec 19–Jan 24", open: false, zone: "South Waterfowl Zone" },
      { name: "Canada Goose", dates: "Sept 1–15 • Oct 24–25 • Oct 31–Jan 26", open: false, zone: "North Waterfowl Zone" },
      { name: "Canada Goose", dates: "Sept 1–15 • Oct 31–Dec 13 • Dec 19–Jan 31", open: false, zone: "Central Waterfowl Zone" },
      { name: "Canada Goose", dates: "Sept 1–15 • Nov 14–Jan 31", open: false, zone: "South Waterfowl Zone" },
      { name: "Light Goose & Brant", dates: "Follows the loaded regular goose dates by zone", open: false, zone: "Select waterfowl zone" },
      { name: "White-fronted Goose", dates: "Oct 31–Jan 26 North • Oct 31–Dec 13 & Dec 19–Jan 31 Central • Nov 14–Jan 31 South", open: false, zone: "Select waterfowl zone" },
    ],
    specialRules: [
      "The former South-Central and South zones are combined into one South Waterfowl Zone beginning with the 2026 season.",
      "Daily bag values below are preseason working values and must be replaced or reconfirmed when IDNR publishes the final 2026–2027 digest.",
      "Scaup timing, public-site permits, check-station procedures and site-specific closures must be confirmed before hunting.",
      "Many IDNR-managed sites use lotteries, daily drawings or location-specific regulations that are more restrictive than statewide rules.",
    ],
    birds: [
      { id: "mallard-drake", label: "Mallard — Drake", group: "Ducks", limit: 4, sex: "Drake", parent: "mallard", parentLimit: 4 },
      { id: "mallard-hen", label: "Mallard — Hen", group: "Ducks", limit: 2, sex: "Hen", parent: "mallard", parentLimit: 4 },
      { id: "wood-duck", label: "Wood Duck", group: "Ducks", limit: 3 },
      { id: "pintail", label: "Northern Pintail", group: "Ducks", limit: 3 },
      { id: "black-duck", label: "American Black Duck", group: "Ducks", limit: 2 },
      { id: "redhead", label: "Redhead", group: "Ducks", limit: 2 },
      { id: "canvasback", label: "Canvasback", group: "Ducks", limit: 2 },
      { id: "scaup", label: "Scaup", group: "Ducks", limit: 2, note: "Preseason working maximum; date-dependent final limit must be verified in the IDNR digest." },
      { id: "mottled-duck", label: "Mottled Duck", group: "Ducks", limit: 1 },
      { id: "other-duck", label: "Other legal duck", group: "Ducks", limit: 6 },
      { id: "hooded-merganser", label: "Hooded Merganser", group: "Other", limit: 2, parent: "merganser", parentLimit: 5 },
      { id: "other-merganser", label: "Other Merganser", group: "Other", limit: 5, parent: "merganser", parentLimit: 5 },
      { id: "coot", label: "Coot", group: "Other", limit: 15 },
      { id: "canada-goose", label: "Canada Goose", group: "Geese", limit: 3, note: "Preseason working value; verify the final IDNR daily limit." },
      { id: "white-fronted-goose", label: "White-fronted Goose", group: "Geese", limit: 2, note: "Preseason working value; verify the final IDNR daily limit." },
      { id: "light-goose", label: "Snow / Blue / Ross’s Goose", group: "Geese", limit: 20, note: "Preseason working value; conservation-order limits differ." },
      { id: "brant", label: "Brant", group: "Geese", limit: 1, note: "Counts with the light-goose season dates; verify the final IDNR limit." },
    ],
  },
  {
    code: "MT", name: "Montana", seasonYear: "2026", dataStatus: "current",
    verifiedLabel: "2026 • official Montana FWP migratory-bird regulations", officialUrl: sources.MT,
    shootingHours: "Generally ½ hour before sunrise to sunset. Canyon Ferry closes at noon during the youth season and October 3–9; other exceptions apply.",
    overview: "Pacific and Central Flyway rules differ. The Pacific Flyway has a seven-bird duck/merganser bag, while Central Flyway Zones 1 and 2 use a six-bird bag and different split dates.",
    zones: ["Pacific Flyway", "Central Flyway — Zone 1", "Central Flyway — Zone 2"],
    duckDailyLimits: { "Pacific Flyway": 7, "Central Flyway — Zone 1": 6, "Central Flyway — Zone 2": 6 },
    seasons: [
      { name: "Youth Waterfowl", dates: "Sept 26–27, 2026", open: false, zone: "Statewide" },
      { name: "Ducks & Mergansers", dates: "Oct 3–Jan 15", open: false, zone: "Pacific Flyway" },
      { name: "Ducks, Mergansers & Coots", dates: "Oct 3–Jan 7", open: false, zone: "Central Flyway — Zone 1" },
      { name: "Ducks, Mergansers & Coots", dates: "Oct 3–11 • Oct 24–Jan 19", open: false, zone: "Central Flyway — Zone 2" },
      { name: "Geese", dates: "Oct 3–Jan 15", open: false, zone: "Pacific Flyway" },
      { name: "Geese", dates: "Oct 3–Jan 15", open: false, zone: "Central Flyway — Zone 1" },
      { name: "Geese", dates: "Oct 3–11 • Oct 24–Jan 27", open: false, zone: "Central Flyway — Zone 2" },
    ],
    specialRules: [
      "The Pacific Flyway covers Hill, Chouteau, Cascade, Meagher and Park counties and all counties west of them; the Central Flyway includes the listed eastern counties and is divided into Zones 1 and 2.",
      "Pacific Flyway scaup close December 27 even though the general duck season continues through January 15.",
      "Central Flyway hunters may take two bonus blue-winged teal in addition to the regular bag during October 3–11.",
      "Coot limits differ by flyway: 25 in the Pacific Flyway and 15 in the Central Flyway.",
      "Canyon Ferry has noon closures September 26–27 and October 3–9; several Cascade County reservoirs are closed to waterfowl hunting.",
    ],
    birds: [
      { id: "mallard-drake", label: "Mallard — Drake", group: "Ducks", limit: 7, sex: "Drake", parent: "mallard", parentLimits: { "Pacific Flyway": 7, "Central Flyway — Zone 1": 5, "Central Flyway — Zone 2": 5 }, zoneLimits: { "Pacific Flyway": 7, "Central Flyway — Zone 1": 5, "Central Flyway — Zone 2": 5 } },
      { id: "mallard-hen", label: "Mallard — Hen", group: "Ducks", limit: 2, sex: "Hen", parent: "mallard", parentLimits: { "Pacific Flyway": 7, "Central Flyway — Zone 1": 5, "Central Flyway — Zone 2": 5 } },
      { id: "wood-duck", label: "Wood Duck", group: "Ducks", limit: 7, zoneLimits: { "Pacific Flyway": 7, "Central Flyway — Zone 1": 3, "Central Flyway — Zone 2": 3 } },
      { id: "pintail", label: "Northern Pintail", group: "Ducks", limit: 3 },
      { id: "redhead", label: "Redhead", group: "Ducks", limit: 2 },
      { id: "canvasback", label: "Canvasback", group: "Ducks", limit: 2 },
      { id: "scaup", label: "Scaup", group: "Ducks", limit: 2, zoneLimits: { "Pacific Flyway": 2, "Central Flyway — Zone 1": 1, "Central Flyway — Zone 2": 1 }, note: "Pacific season closes Dec 27; Central Flyway limit is one." },
      { id: "hooded-merganser", label: "Hooded Merganser", group: "Ducks", limit: 7, zoneLimits: { "Pacific Flyway": 7, "Central Flyway — Zone 1": 2, "Central Flyway — Zone 2": 2 } },
      { id: "other-merganser", label: "Other Merganser", group: "Ducks", limit: 7, zoneLimits: { "Pacific Flyway": 7, "Central Flyway — Zone 1": 6, "Central Flyway — Zone 2": 6 } },
      { id: "other-duck", label: "Other legal duck", group: "Ducks", limit: 7, zoneLimits: { "Pacific Flyway": 7, "Central Flyway — Zone 1": 6, "Central Flyway — Zone 2": 6 } },
      { id: "bonus-bluewing-teal", label: "Bonus Blue-winged Teal", group: "Other", limit: 2, note: "Additional to the six-bird Central Flyway bag only Oct 3–11." },
      { id: "coot", label: "Coot", group: "Other", limit: 25, zoneLimits: { "Pacific Flyway": 25, "Central Flyway — Zone 1": 15, "Central Flyway — Zone 2": 15 } },
      { id: "dark-goose", label: "Dark Goose", group: "Geese", limit: 5, note: "All geese other than snow, blue and Ross’s geese." },
      { id: "light-goose", label: "Snow / Blue / Ross’s Goose", group: "Geese", limit: 20 },
    ],
  },
  {
    code: "MN", name: "Minnesota", seasonYear: "2026", dataStatus: "current",
    verifiedLabel: "2026 • official Minnesota DNR package", officialUrl: sources.MN,
    sourceLinks: [
      { label: "Minnesota duck and goose dates", url: sources.MN },
      { label: "Minnesota DNR waterfowl hub", url: "https://www.dnr.state.mn.us/hunting/waterfowl/index.html" },
    ],
    shootingHours: "½ hour before sunrise to sunset, except early teal when shooting begins at sunrise.",
    overview: "North, Central and South waterfowl zones with split seasons in the Central and South zones, date-dependent scaup limits and reservation-specific early-teal restrictions.",
    zones: ["North Waterfowl Zone", "Central Waterfowl Zone", "South Waterfowl Zone"],
    seasons: [
      { name: "Early Teal", dates: "Sept 5–9, 2026", open: false, zone: "Statewide" },
      { name: "Youth Waterfowl", dates: "Sept 12–13, 2026", open: false, zone: "Statewide" },
      { name: "Early Goose", dates: "Sept 12–27, 2026", open: false, zone: "Statewide" },
      { name: "Ducks, Coots & Mergansers", dates: "Sept 26–Nov 24", open: false, zone: "North Waterfowl Zone" },
      { name: "Ducks, Coots & Mergansers", dates: "Sept 26–Oct 4 • Oct 10–Nov 29", open: false, zone: "Central Waterfowl Zone" },
      { name: "Ducks, Coots & Mergansers", dates: "Sept 26–Oct 4 • Oct 17–Dec 6", open: false, zone: "South Waterfowl Zone" },
      { name: "Regular Goose", dates: "Sept 26–Dec 25", open: false, zone: "North Waterfowl Zone" },
      { name: "Regular Goose", dates: "Sept 26–Oct 4 • Oct 10–Dec 30", open: false, zone: "Central Waterfowl Zone" },
      { name: "Regular Goose", dates: "Sept 26–Oct 4 • Oct 17–Jan 6", open: false, zone: "South Waterfowl Zone" },
    ],
    specialRules: [
      "Scaup: North Zone allows one through October 10 and two afterward; Central allows one through October 15 and two afterward; South allows one through October 22 and two afterward, within open season dates.",
      "Early-teal restrictions apply on identified wild-rice waters within the Mille Lacs, Leech Lake and White Earth reservation boundaries; contact the tribal authority before hunting.",
      "Canada, white-fronted geese and brant share a five-bird combined limit; light geese have a separate 20-bird limit.",
      "The possession limit for migratory birds is three times the daily limit.",
      "Only federally approved nontoxic shot may be possessed while taking waterfowl, coots, moorhens or sandhill cranes.",
    ],
    birds: [
      { id: "mallard-drake", label: "Mallard — Drake", group: "Ducks", limit: 4, sex: "Drake", parent: "mallard", parentLimit: 4 },
      { id: "mallard-hen", label: "Mallard — Hen", group: "Ducks", limit: 2, sex: "Hen", parent: "mallard", parentLimit: 4 },
      { id: "wood-duck", label: "Wood Duck", group: "Ducks", limit: 3 },
      { id: "black-duck", label: "American Black Duck", group: "Ducks", limit: 2 },
      { id: "pintail", label: "Northern Pintail", group: "Ducks", limit: 2 },
      { id: "redhead", label: "Redhead", group: "Ducks", limit: 2 },
      { id: "canvasback", label: "Canvasback", group: "Ducks", limit: 2 },
      { id: "scaup", label: "Scaup", group: "Ducks", limit: 2, note: "The one- or two-bird limit changes by zone and date; see the loaded restrictions." },
      { id: "other-duck", label: "Other legal duck", group: "Ducks", limit: 6 },
      { id: "hooded-merganser", label: "Hooded Merganser", group: "Other", limit: 2, parent: "merganser", parentLimit: 5, note: "Mergansers have a separate five-bird aggregate limit." },
      { id: "other-merganser", label: "Other Merganser", group: "Other", limit: 5, parent: "merganser", parentLimit: 5 },
      { id: "coot-moorhen", label: "Coot / Moorhen", group: "Other", limit: 15 },
      { id: "dark-goose", label: "Canada / White-fronted Goose / Brant", group: "Geese", limit: 5 },
      { id: "light-goose", label: "Snow / Blue / Ross’s Goose", group: "Geese", limit: 20 },
    ],
  },
  {
    code: "KS", name: "Kansas", seasonYear: "2026–2027", dataStatus: "current",
    verifiedLabel: "2026–2027 • official Kansas Wildlife & Parks package", officialUrl: sources.KS,
    shootingHours: "Generally ½ hour before sunrise to sunset. Early teal and special-season rules must be checked in the current KDWP regulations.",
    overview: "High Plains and three Low Plains duck zones with split seasons, zone-specific youth/veteran/military dates and separate regular goose seasons.",
    zones: ["High Plains Unit", "Low Plains Early Zone", "Low Plains Late Zone", "Low Plains Southeast Zone"],
    seasons: [
      { name: "Early Teal", dates: "Sept 19–27, 2026", open: false, zone: "High Plains Unit" },
      { name: "Early Teal", dates: "Sept 12–20, 2026", open: false, zone: "All Low Plains Zones" },
      { name: "Ducks, Mergansers & Coots", dates: "Oct 10–Jan 3 • Jan 22–31", open: false, zone: "High Plains Unit" },
      { name: "Ducks, Mergansers & Coots", dates: "Oct 10–Dec 6 • Dec 19–Jan 3", open: false, zone: "Low Plains Early Zone" },
      { name: "Ducks, Mergansers & Coots", dates: "Oct 31–Jan 3 • Jan 23–31", open: false, zone: "Low Plains Late Zone" },
      { name: "Ducks, Mergansers & Coots", dates: "Nov 7–Jan 3 • Jan 16–31", open: false, zone: "Low Plains Southeast Zone" },
      { name: "Canada & Cackling Geese", dates: "Oct 31–Nov 1 • Nov 4–Feb 14", open: false, zone: "Statewide" },
      { name: "White-fronted Geese", dates: "Oct 31–Jan 3 • Jan 23–Feb 14", open: false, zone: "Statewide" },
      { name: "Light Geese", dates: "Oct 31–Nov 1 • Nov 4–Feb 14", open: false, zone: "Statewide" },
      { name: "Light Goose Conservation Order", dates: "Feb 15–Apr 30, 2027", open: false, zone: "Statewide" },
    ],
    specialRules: [
      "Ducks and mergansers share one six-bird aggregate daily bag.",
      "Youth, veteran and active-military waterfowl dates differ among the High Plains and three Low Plains zones.",
      "Canada and cackling geese have a six-bird daily limit; white-fronted geese have a two-bird limit; light geese have a 50-bird regular-season limit.",
      "The Light Goose Conservation Order has no daily or possession limit and allows special methods only under the applicable order rules.",
      "Wildlife-area access, refuge boundaries and area-specific closures must be checked before hunting.",
    ],
    birds: [
      { id: "mallard-drake", label: "Mallard — Drake", group: "Ducks", limit: 5, sex: "Drake", parent: "mallard", parentLimit: 5 },
      { id: "mallard-hen", label: "Mallard — Hen", group: "Ducks", limit: 2, sex: "Hen", parent: "mallard", parentLimit: 5 },
      { id: "wood-duck", label: "Wood Duck", group: "Ducks", limit: 3 },
      { id: "pintail", label: "Northern Pintail", group: "Ducks", limit: 3 },
      { id: "redhead", label: "Redhead", group: "Ducks", limit: 2 },
      { id: "canvasback", label: "Canvasback", group: "Ducks", limit: 2 },
      { id: "scaup", label: "Scaup", group: "Ducks", limit: 2 },
      { id: "merganser", label: "Merganser", group: "Ducks", limit: 6, note: "Included in the aggregate six-bird duck and merganser limit." },
      { id: "other-duck", label: "Other legal duck", group: "Ducks", limit: 6 },
      { id: "early-teal", label: "Early-season Teal", group: "Other", limit: 6, note: "Separate early teal season only." },
      { id: "coot", label: "Coot", group: "Other", limit: 15 },
      { id: "canada-goose", label: "Canada / Cackling Goose", group: "Geese", limit: 6 },
      { id: "white-fronted-goose", label: "White-fronted Goose", group: "Geese", limit: 2 },
      { id: "light-goose", label: "Snow / Blue / Ross’s Goose", group: "Geese", limit: 50 },
    ],
  },
];
