import type { BirdRule, HuntCategoryId } from "./types";

export type HuntCategory = {
  id: HuntCategoryId;
  label: string;
  shortLabel: string;
  icon: string;
  description: string;
  rulesMode: "waterfowl-live" | "field-log";
  species: BirdRule[];
};

const rule = (categoryId: HuntCategoryId, id: string, label: string, group: BirdRule["group"], icon: string): BirdRule => ({
  id: `${categoryId}-${id}`,
  label,
  group,
  icon,
  huntCategory: categoryId,
  limit: 999,
});

export const huntCategories: HuntCategory[] = [
  {
    id: "waterfowl",
    label: "Waterfowl",
    shortLabel: "Waterfowl",
    icon: "🦆",
    description: "Ducks, geese, swans, coots, and other loaded waterfowl.",
    rulesMode: "waterfowl-live",
    species: [],
  },
  {
    id: "deer",
    label: "Deer",
    shortLabel: "Deer",
    icon: "🦌",
    description: "Whitetail, mule deer, black-tailed deer, and other legal deer.",
    rulesMode: "field-log",
    species: [
      rule("deer", "whitetail-buck", "Whitetail — Buck", "Deer", "🦌"),
      rule("deer", "whitetail-doe", "Whitetail — Doe", "Deer", "🦌"),
      rule("deer", "mule-buck", "Mule Deer — Buck", "Deer", "🦌"),
      rule("deer", "mule-doe", "Mule Deer — Doe", "Deer", "🦌"),
      rule("deer", "blacktail-buck", "Black-tailed Deer — Buck", "Deer", "🦌"),
      rule("deer", "blacktail-doe", "Black-tailed Deer — Doe", "Deer", "🦌"),
      rule("deer", "coues-buck", "Coues Whitetail — Buck", "Deer", "🦌"),
      rule("deer", "coues-doe", "Coues Whitetail — Doe", "Deer", "🦌"),
      rule("deer", "sitka-buck", "Sitka Black-tailed Deer — Buck", "Deer", "🦌"),
      rule("deer", "sitka-doe", "Sitka Black-tailed Deer — Doe", "Deer", "🦌"),
      rule("deer", "other", "Other Legal Deer", "Deer", "🦌"),
    ],
  },
  {
    id: "turkey",
    label: "Wild Turkey",
    shortLabel: "Turkey",
    icon: "🦃",
    description: "Spring and fall turkey field logs with sex and age choices.",
    rulesMode: "field-log",
    species: [
      rule("turkey", "tom", "Wild Turkey — Tom", "Turkey", "🦃"),
      rule("turkey", "jake", "Wild Turkey — Jake", "Turkey", "🦃"),
      rule("turkey", "hen", "Wild Turkey — Hen", "Turkey", "🦃"),
      rule("turkey", "unspecified", "Wild Turkey — Unspecified", "Turkey", "🦃"),
    ],
  },
  {
    id: "dove-migratory",
    label: "Dove & Migratory Birds",
    shortLabel: "Dove & Migratory",
    icon: "🕊️",
    description: "Dove, woodcock, snipe, rails, gallinules, cranes, and pigeons.",
    rulesMode: "field-log",
    species: [
      rule("dove-migratory", "mourning-dove", "Mourning Dove", "Migratory Birds", "🕊️"),
      rule("dove-migratory", "white-winged-dove", "White-winged Dove", "Migratory Birds", "🕊️"),
      rule("dove-migratory", "eurasian-dove", "Eurasian Collared-Dove", "Migratory Birds", "🕊️"),
      rule("dove-migratory", "band-tailed-pigeon", "Band-tailed Pigeon", "Migratory Birds", "🕊️"),
      rule("dove-migratory", "woodcock", "American Woodcock", "Migratory Birds", "🐦"),
      rule("dove-migratory", "snipe", "Wilson’s Snipe", "Migratory Birds", "🐦"),
      rule("dove-migratory", "sora-rail", "Sora / Rail", "Migratory Birds", "🐦"),
      rule("dove-migratory", "gallinule", "Gallinule", "Migratory Birds", "🐦"),
      rule("dove-migratory", "sandhill-crane", "Sandhill Crane", "Migratory Birds", "🐦"),
      rule("dove-migratory", "crow", "Crow", "Migratory Birds", "🐦"),
      rule("dove-migratory", "other", "Other Legal Migratory Game Bird", "Migratory Birds", "🐦"),
    ],
  },
  {
    id: "upland-birds",
    label: "Upland Game Birds",
    shortLabel: "Upland Birds",
    icon: "🐦",
    description: "Pheasant, quail, grouse, chukar, partridge, and ptarmigan.",
    rulesMode: "field-log",
    species: [
      rule("upland-birds", "pheasant-rooster", "Ring-necked Pheasant — Rooster", "Upland Birds", "🐦"),
      rule("upland-birds", "pheasant-hen", "Ring-necked Pheasant — Hen", "Upland Birds", "🐦"),
      rule("upland-birds", "bobwhite", "Northern Bobwhite", "Upland Birds", "🐦"),
      rule("upland-birds", "scaled-quail", "Scaled Quail", "Upland Birds", "🐦"),
      rule("upland-birds", "gambels-quail", "Gambel’s Quail", "Upland Birds", "🐦"),
      rule("upland-birds", "california-quail", "California Quail", "Upland Birds", "🐦"),
      rule("upland-birds", "mountain-quail", "Mountain Quail", "Upland Birds", "🐦"),
      rule("upland-birds", "chukar", "Chukar", "Upland Birds", "🐦"),
      rule("upland-birds", "hungarian-partridge", "Hungarian Partridge", "Upland Birds", "🐦"),
      rule("upland-birds", "ruffed-grouse", "Ruffed Grouse", "Upland Birds", "🐦"),
      rule("upland-birds", "spruce-grouse", "Spruce Grouse", "Upland Birds", "🐦"),
      rule("upland-birds", "sharp-tailed-grouse", "Sharp-tailed Grouse", "Upland Birds", "🐦"),
      rule("upland-birds", "prairie-chicken", "Prairie Chicken", "Upland Birds", "🐦"),
      rule("upland-birds", "sage-grouse", "Sage Grouse", "Upland Birds", "🐦"),
      rule("upland-birds", "ptarmigan", "Ptarmigan", "Upland Birds", "🐦"),
      rule("upland-birds", "other", "Other Legal Upland Game Bird", "Upland Birds", "🐦"),
    ],
  },
  {
    id: "big-game",
    label: "Other Big Game",
    shortLabel: "Big Game",
    icon: "🐻",
    description: "Elk, moose, pronghorn, bear, sheep, goat, caribou, bison, and legal hogs.",
    rulesMode: "field-log",
    species: [
      rule("big-game", "elk-bull", "Elk — Bull", "Big Game", "🫎"),
      rule("big-game", "elk-cow", "Elk — Cow", "Big Game", "🫎"),
      rule("big-game", "moose-bull", "Moose — Bull", "Big Game", "🫎"),
      rule("big-game", "moose-cow", "Moose — Cow", "Big Game", "🫎"),
      rule("big-game", "pronghorn-buck", "Pronghorn — Buck", "Big Game", "🦌"),
      rule("big-game", "pronghorn-doe", "Pronghorn — Doe", "Big Game", "🦌"),
      rule("big-game", "black-bear", "Black Bear", "Big Game", "🐻"),
      rule("big-game", "brown-bear", "Brown / Grizzly Bear", "Big Game", "🐻"),
      rule("big-game", "mountain-goat", "Mountain Goat", "Big Game", "🐐"),
      rule("big-game", "bighorn-sheep", "Bighorn Sheep", "Big Game", "🐏"),
      rule("big-game", "dall-sheep", "Dall Sheep", "Big Game", "🐏"),
      rule("big-game", "caribou", "Caribou", "Big Game", "🦌"),
      rule("big-game", "bison", "American Bison", "Big Game", "🐂"),
      rule("big-game", "muskox", "Muskox", "Big Game", "🐂"),
      rule("big-game", "wild-pig", "Wild Pig / Feral Hog", "Big Game", "🐗"),
      rule("big-game", "javelina", "Javelina / Collared Peccary", "Big Game", "🐗"),
      rule("big-game", "alligator", "American Alligator", "Big Game", "🐊"),
      rule("big-game", "mountain-lion", "Mountain Lion", "Big Game", "🐾"),
      rule("big-game", "other", "Other Legal Big Game", "Big Game", "🐾"),
    ],
  },
  {
    id: "small-game",
    label: "Small Game",
    shortLabel: "Small Game",
    icon: "🐇",
    description: "Rabbit, hare, squirrel, raccoon, opossum, groundhog, and nutria.",
    rulesMode: "field-log",
    species: [
      rule("small-game", "cottontail", "Cottontail Rabbit", "Small Game", "🐇"),
      rule("small-game", "snowshoe-hare", "Snowshoe Hare", "Small Game", "🐇"),
      rule("small-game", "jackrabbit", "Jackrabbit", "Small Game", "🐇"),
      rule("small-game", "gray-squirrel", "Gray Squirrel", "Small Game", "🐿️"),
      rule("small-game", "fox-squirrel", "Fox Squirrel", "Small Game", "🐿️"),
      rule("small-game", "red-squirrel", "Red Squirrel", "Small Game", "🐿️"),
      rule("small-game", "raccoon", "Raccoon", "Small Game", "🦝"),
      rule("small-game", "opossum", "Opossum", "Small Game", "🐾"),
      rule("small-game", "groundhog", "Groundhog", "Small Game", "🐾"),
      rule("small-game", "nutria", "Nutria", "Small Game", "🐾"),
      rule("small-game", "other", "Other Legal Small Game", "Small Game", "🐾"),
    ],
  },
  {
    id: "predator-furbearer",
    label: "Predators & Furbearers",
    shortLabel: "Predators",
    icon: "🐺",
    description: "Coyote, fox, bobcat, beaver, otter, muskrat, mink, and others.",
    rulesMode: "field-log",
    species: [
      rule("predator-furbearer", "coyote", "Coyote", "Predators & Furbearers", "🐺"),
      rule("predator-furbearer", "red-fox", "Red Fox", "Predators & Furbearers", "🦊"),
      rule("predator-furbearer", "gray-fox", "Gray Fox", "Predators & Furbearers", "🦊"),
      rule("predator-furbearer", "bobcat", "Bobcat", "Predators & Furbearers", "🐾"),
      rule("predator-furbearer", "raccoon", "Raccoon", "Predators & Furbearers", "🦝"),
      rule("predator-furbearer", "badger", "Badger", "Predators & Furbearers", "🐾"),
      rule("predator-furbearer", "beaver", "Beaver", "Predators & Furbearers", "🐾"),
      rule("predator-furbearer", "river-otter", "River Otter", "Predators & Furbearers", "🦦"),
      rule("predator-furbearer", "muskrat", "Muskrat", "Predators & Furbearers", "🐾"),
      rule("predator-furbearer", "mink", "Mink", "Predators & Furbearers", "🐾"),
      rule("predator-furbearer", "weasel", "Weasel", "Predators & Furbearers", "🐾"),
      rule("predator-furbearer", "skunk", "Skunk", "Predators & Furbearers", "🐾"),
      rule("predator-furbearer", "other", "Other Legal Furbearer", "Predators & Furbearers", "🐾"),
    ],
  },
  {
    id: "other-game",
    label: "Other Legal Game",
    shortLabel: "Other Game",
    icon: "✚",
    description: "A flexible field log for another lawfully hunted species.",
    rulesMode: "field-log",
    species: [rule("other-game", "other", "Other Legal Game", "Other Game", "✚")],
  },
];

export const huntCategoryById = (id: HuntCategoryId) => huntCategories.find((category) => category.id === id) ?? huntCategories[0];
